### ISSUE TITLE
It takes a second to reorder tabs in a list after switching between tabs - bug or feature?

### ISSUE THREAD

**Issue by MInner** [babyman/quick-tabs-chrome-extension#103]
Hi,

the extension is totally amazing, but I have noticed some weird behavior recently; I'm not quite sure if that is a bug or a feature, though. When I switch from tab A (let's say using Alt-Tab) to tab B, the background of a number plate on the extension icon turns yellow (usually it is blue) for a second, and if I press the keyboard shortcut for the quick-tabs extension while it is yellow, it shows me the "old" (the way it was while I was on tab A) ordering of the tabs so A (as a "current page") is the end of the list (and should probably be on the top as soon as this is current "last visited tab").

I don't know if I'm the the only one who uses the extension this particular way, but I do usually open new tab, open the tab list and close the close one quite often. Or use the "<extensionshortcut> + Enter" sequence as a "last visited tab" shortcut quite often, so this kind of behavior turns out to be somewhat not quite useful (if that was planned as a feature, but I personally can't actually come up with any possible use of such a feature :( )

Thank you!

Ben

**Comment by babyman** [comment]
Hi Ben,

This is actually by design, the short delay before the update is to prevent the extension tracking tabs when you move through them using Ctrl+Tab (or in my case Cmd+Left/Right Arrow), see #90.

Also by delaying the order update the next/prev keyboard shortcuts can work without loading the popup window:

> * Select previous tab without loading the popup window
* Select next tab without loading the popup window
* IMPORTANT the 'next tab' shortcut is only available for a second or so (while the badge text is orange) before the current tab is moved to the top of the MRU list.

These shortcuts are not mapped by default but I have Cmd+J and Cmd+K mapped.

Evan

**Comment by MInner** [comment]
Well, okay, I never "hold down Ctrl+Tab until I hit the tab", but okay, the shortcut you've mentioned solves the deal somehow :) cool, thank you

That might seem like a "hardcode logic" or "logic overhead", but it seem quite reasonable for me: if the user has history <...>, starts from tab A, goes through B, C, D, stops at tab F and presses quicktab shortcut immediately after reaching it, he should (within the logic of the ticket you mentioned) probably see the "last visited tabs" in ordering like: "A, <...>", not "<...>", right?

**Comment by babyman** [comment]
Yep, sounds about right, if you start with tabs ABCD in that order in QuickTabs and ctrl+tab from A through B and C stopping at D at that exact moment QT still has the tab order as ABCD.  After about 1.5 seconds it will update the tab order to DABC (and switch the tab count background back to blue).

If that delay is really getting in the way I could add an option to configure it but that might make things even more confusing for people.

E

**Comment by MInner** [comment]
Right. I just think that this kind of behavior would be little bit more intuitive: if person has tabs ABCD and ctr+tabs from A to D and calls an extension, it should (probably) figure out that he is going to "stay here" and show him an ordering "DABC" immediately; the purpose of the delay, if I understand correctly, is to make it DABC, not DCBA (in the very end) - and that is perfectly fine, make sense and even useful. But what if it would work as follows: when user presses an extension icon button, he "resets this orange 1.5 sec timer to zero" == (regardless of timers actual value) forces an extension to recompute an ordering considering current tab to be the last one visited? Let me know if I describe what I mean in a messy way or the use can is not so clear.

**Comment by babyman** [comment]
Right, I will take a look and see how best to implement this.
