### ISSUE TITLE
Feature Request: Exact match

### ISSUE THREAD

**Issue by nizdobs** [babyman/quick-tabs-chrome-extension#106]
I'd like to have an option to specify that search results only match when they exactly match my search string.  f I search for "cricket" I don't want to see results matching on "javascript" or "ticket".

**Comment by babyman** [comment]
Hi @nizdobs,

Thanks for your feedback, the fuzzy search seems to be an issue and I will take a look at how to improve it, there has been some discussion here, #97.

Evan
