### ISSUE TITLE
Close when focusing on address bar

### ISSUE THREAD

**Issue by nodkrot** [babyman/quick-tabs-chrome-extension#107]
Given I press <kbd>cmd</kbd>+<kbd>E</kbd> - quick tabs dropdown shows
Then I want to use chrome shortcut to focus on the address bar <kbd>cmd</kbd>+<kbd>L</kbd> - quick tabs dropdown should close.

**Comment by babyman** [comment]
I see the issue, Chrome highlights the address bar content but sends the key presses to the Quick Tabs search field.

**Comment by nodkrot** [comment]
Yeah it focuses but it still types in quick tabs search

**Comment by babyman** [comment]
Looks like the Chrome guys have fixed this :)
