### ISSUE TITLE
Feature Request: Exclude bookmarks from search

### ISSUE THREAD

**Issue by JoelAzaria** [babyman/quick-tabs-chrome-extension#115]
I would like an option in the settings to exclude my bookmarks from being searched by Quick Tabs.

I often use my laptop for customer demos or review of work in progress and may be showing items across multiple tabs and apps.  On a few occasions I've used QT to find a tab and seemingly innocuous search terms returned 'inappropriate' results from my bookmarks (results that might allude to or name a competitor or divulge a client name for example.)   For my use case I never use QT to search my bookmarks and don't expect I'll ever have a reason to so I'd prefer to simply have them excluded from search completely.

I hope it's not a very difficult request.  If there's a way to accomplish it now (eg. maybe with the regex exclude) I'd be happy to have it pointed out.

Otherwise very useful (and comfortable/easy to use) extension - thank you for it.

J.

**Comment by JayGoldberg** [comment]
Would have liked to have this as well...if nothing but to speed up search.
