### ISSUE TITLE
on multiple screens the menu appears only on one screen

### ISSUE THREAD

**Issue by eurochriskelly** [babyman/quick-tabs-chrome-extension#117]
A strange effect I've noticed which I think comes from having multiple screens attached.

On one of the screens, in chrome, the menu appears normal. In the others, it only partially appears or does not appear at all. e.g.

![image](https://cloud.githubusercontent.com/assets/622956/12712469/e1e8fce2-c8c8-11e5-9b74-6501f0dfe216.png)

Usually there is one master screen where everything works fine. However, to use the extension would require moving the chrome tab over to that screen which take away from the convenience of the plugin.

Is this issue know and are there any workarounds?

**Comment by babyman** [comment]
This seem similar to #91, are you running OSX?

**Comment by eurochriskelly** [comment]
Never noticed reply before. FYI, I was running windows 10.
