### ISSUE TITLE
Launch shortcut stopped working on Mac

### ISSUE THREAD

**Issue by pblesi** [babyman/quick-tabs-chrome-extension#123]
The Shortcut I set for the popup (Cmd+s) has stopped working for me. I additionally tried Cmd+E and that does not work either. Nothing happens when I press it. I have tried removing and reinstalling the extension. This is my version of chrome: Version 48.0.2564.116 (64-bit)

**Comment by kapman** [comment]
Same here, but the pop up just opens and closes really quickly. I can see it it quickly fade in and then out.

This problem started happening after the chrome update that lets you choose which extensions you see next to the address bar and which are hidden in the burger menu. 

This might be useful: https://groups.google.com/a/chromium.org/forum/#!searchin/chromium-extensions/upcoming/chromium-extensions/7As9MKhav5E/dNiZDoSCCQAJ

**Comment by babyman** [comment]
Thanks for reporting this, I am also experiencing it now that my browser updated to 49.0.2623.87, it seems to impact any extension I map a keyboard shortcut to "activate the extension", the other keyboard mappings still work.  It's strange that I cannot find any bug reports that relate to this being a broader issue, I will keep digging.

**Comment by babyman** [comment]
I found this but it seems old... https://bugs.chromium.org/p/chromium/issues/detail?id=497188&q=extension%20keyboard%20shortcuts&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

I just realized the example extension is QuickTabs!

**Comment by babyman** [comment]
OK, I deleted Chrome off my mac, re-downloaded it from https://www.google.com/chrome/ and reinstalled it.  The extension seems to be working correctly now, possibly an issue in the chrome update process?

I'm going to close this ticket for the moment but if there is still an issue after you try reinstalling please reopen it and I will look into it further =)

**Comment by kapman** [comment]
It only starts happening after you click on an extension that's hidden inside the burger menu. Restarting chrome fixes the issue. I haven't tried uninstalling chrome but could you see if the issue persists even after uninstalling?

**Comment by babyman** [comment]
@kapman I thought it had fixed the issue but it didn't.

If I assign a shortcut to other extensions they also fail to display their popup window, this is starting to smell like a Chrome issue :(

**Comment by babyman** [comment]
I have opened a new ticket with the Chrome guys here https://bugs.chromium.org/p/chromium/issues/detail?id=594420 please add any other information I may have missed =)

**Comment by pblesi** [comment]
I was able to resolve the issue by rebooting chrome and my computer.

**Comment by babyman** [comment]
@pblesi I tried doing the full system reboot (I also tried deleting and re-downloading Chrome) but I am still experiencing this issue.  I notice you are using the older 48.x version of Chrome (my version is 49.0.2623.87 (64-bit)), has your Chrome updated?

**Comment by rcherny** [comment]
Does anyone have a workaround or is the restart really the only way around this? Wow that's awful ...

**Comment by rcherny** [comment]
Ok, so it's a niche market and very specific, but I was able to get it to work via Keyboard Maestro in the meantime using this guy's AppleScript example:

https://forum.keyboardmaestro.com/t/click-chrome-extension-button/2909/6

(hey it's a hack but it works 👍  )

**Comment by babyman** [comment]
@rcherny thanks for sharing the workaround.  This bug is brutal, my best suggestion would be to bump the open chrome ticket and hopefully create enough action for someone to at least review it, that way someone might pick it up and fix it :|

**Comment by pblesi** [comment]
For the record. I was able to fix it, but only temporarily. It seems to work after system reboot, but then stops working after a period of time. I'm not sure what the exact trigger is.

**Comment by babyman** [comment]
@pblesi restarting Chrome should be enough to resolve the issue until you next use the burger menu.

**Comment by jakubka** [comment]
For me, shortcut stops working after I plug or unplug a monitor and chrome moves to another display. Although it doesn't happen always.. feels random. :/ Restarting chrome makes shortcut work again.

**Comment by babyman** [comment]
Hi All, my Chrome version just updated to "Version 52.0.2743.82 (64-bit)" and the extension shortcut seems to be working even after accessing the burger menu.

Let me know if you experience the same thing and I will close this bug (finally) =)

Evan
