### ISSUE TITLE
Updated custom CSS for your latest revision

### ISSUE THREAD

**Issue by fcherman** [babyman/quick-tabs-chrome-extension#125]
Babyman, your recent update broke my custom CSS (the text was too wide to fit on the button, so it slipped off the bottom). I've fixed it by changing the .url and .title widths to 71% rather than 75%.

The complete, updated CSS is at https://userstyles.org/styles/99938/better-styling-for-chrome-extension-quick-tabs and is also pasted below.

This is still one of my very favorite Chrome extensions, and I promote it to everyone I know. Keep up the good work!

Frances 

/*v3 Updated 3.25.16*/

body {
max-height: 600px;
width:750px;
}

div {
box-sizing:border-box;
}

.qs_wrapper {
float:left;
width:100%;
margin:0 0 4px 0;
padding-left: 10px;
}

.qs_input {
margin: 4px 0 0 0px;
height:32px;
width:97%;
border-radius: 5px;
display: block;
float: left;
background-color: rgb(215, 235, 139);
border: 1px solid rgb(153, 153, 153);
}

.tab, .bookmark, div.separator.big {
border: 1px solid #D2CCCC;
padding: 5px;
/* padding-bottom: 5px; */
border-radius: 5px;
margin-bottom: 3px;
margin-right: 2%;
box-shadow: 2px 2px 5px #aaa;
width: 31%;
float:left;
display:inline;
/*color: rgb(32,61,116);*/
clear:none;
color: rgb(29, 101, 158);
font-weight: 500;
background-image: -moz-linear-gradient(top,  rgba(0,0,0,0) 0%, rgba(122,122,122,0.18) 99%, rgba(122,122,122,0.18) 100%);
background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(0,0,0,0)), color-stop(99%,rgba(122,122,122,0.18)), color-stop(100%,rgba(122,122,122,0.18)));
background-image: -webkit-linear-gradient(top,  rgba(0,0,0,0) 0%,rgba(122,122,122,0.18) 99%,rgba(122,122,122,0.18) 100%);
background-image: -o-linear-gradient(top,  rgba(0,0,0,0) 0%,rgba(122,122,122,0.18) 99%,rgba(122,122,122,0.18) 100%);
background-image: -ms-linear-gradient(top,  rgba(0,0,0,0) 0%,rgba(122,122,122,0.18) 99%,rgba(122,122,122,0.18) 100%);
background-image: linear-gradient(to bottom,  rgba(0,0,0,0) 0%,rgba(122,122,122,0.18) 99%,rgba(122,122,122,0.18) 100%);
overflow: hidden;
height: 3.5em;
}

div.tabimage img {
vertical-align: middle;
padding: 4px;
padding-left: 0;
}

div.content {
margin: 4px 0;
padding:0;
padding-left: 10px;
float: left;
height:600px;
width:100%;
}

.highlight {
text-decoration: none;
border-bottom-width:1px;
border-bottom-style:dotted;
}

.withfocus {
background-color: rgba(255,146,10,.7);
}

div.closed {
background-image: none;
opacity: .6;
color: #555;
}

div.closed.withfocus {background-color:rgba(255,146,10,.4);
}

div.closed.withfocus div.title {
background-color: transparent;
}

div.url {
color: #777;
  width: 71%;
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
}

div.close {
float: right;
display: inline;
opacity: .5;
border: 1px solid #999191;
background-color: #F1EEA0;
border-radius: 3px;
top: 0 !important;
right: 0 !important;
}

div.withfocus.open div.close {
top: 0 !important;
right: 0 !important;
}
div.close:hover {
opacity:1;
background-color: rgb(235, 19, 19) !important;
}

.title {
overflow: hidden; 
width: 71%;
}

div.separator.big {
  color: #212121;
    height: 2em;
font-size:12px;
  background-color: rgb(198, 212, 255);
padding:0;
width:97%
}

div.separator.big:before, div.separator.big:after {
  content: "▼";
}

div.separator.big span {
  vertical-align: baseline; 
}

 .withfocus div.title, div.closed.withfocus div.title, .withfocus div.url {
  background-color: transparent;
  color: inherit;
}

div.tabimage img {
background-color:transparent;
}

.bookmark div {
background-color:transparent;
}

.bookmark {
  background-color: rgb(230, 240, 190);
  border-top: 1px solid rgba(0, 0, 0, 0.07);
}

.withfocus {
  background-color: rgba(255, 146, 10, 0.7) !important;
  color:#777;
}

**Comment by babyman** [comment]
Thanks for the update and all your support Frances =)
