### ISSUE TITLE
Use cmd+n/cmd+p to traverse the list

### ISSUE THREAD

**Issue by simonsmith** [babyman/quick-tabs-chrome-extension#126]
This mimics the behaviour found in the Chrome address bar.

Loving the extension so far :+1:

**Comment by babyman** [comment]
Thanks for the feedback, I'm glad you are enjoying the extension.

I think you could map cmd+n/cmd+p using the keyboard shortcuts dialog at the bottom of the Chrome Extensions page but on my system (OSX) those keys open a new Chrome window and open the print dialog respectively.
