### ISSUE TITLE
Incomprehensible switch order

### ISSUE THREAD

**Issue by slikts** [babyman/quick-tabs-chrome-extension#131]
As I'm typing this, I switch to a different tab, then press Ctrl+K (Quick previous tab), expecting to switch back to this tab, but instead I'm getting a seemingly random tab. It took searching the issues here to find out that there's an arbitrary hardcoded delay before the tab order is updated. It's the opposite of "quick" and is very confusing, especially since there's no explanation of this, and instead the extension description refers to MRU switching in IntelliJ IDEA, which I'm fairly certain works *nothing* like this.

**Comment by babyman** [comment]
@slikts thank you for taking the time to file this, the popup-less tab navigation can take a little getting used to, it's a tough thing to visualize but it is described in the features (any suggestion to improve this would be welcome)

> Chrome keyboard shortcuts (configured using the keyboard shortcuts dialog at the bottom of the Chrome Extensions page):
* Shortcut key to launch popup window from most tabs (default ctrl+e).
* Select previous tab without loading the popup window
* Select next tab without loading the popup window
* **IMPORTANT the 'next tab' shortcut is only available for a second or so (while the badge text is orange) before the current tab is moved to the top of the MRU list.**

You can quickly switch between tabs using Ctrl+K followed by Ctrl+J, this will work until a tab is displayed for the "arbitrary hardcoded delay" (see #90 for some backstory) then it is moved to the top of the list and Ctrl+J will no longer do anything, Ctrl+K will take you the previous tab as shown in the popup.

Of course if this does not work for you it is possible to simply use the popup tab list (Ctrl+E) to navigate tabs.

This functionality is much like using IntelliJ IDEA's Opt+Cmd+Left/Right Arrow keys but with some allowances for Chromes keyboard shortcut functionality and the fact that we are navigating browser tabs and not source code.

**Comment by slikts** [comment]
IntelliJ IDEA has no such delay, and this implementation of MRU switching is very different, because switching back and forth between tabs (the main use case for MRU switching) is either broken or slow, making your use of the word "quick" ironic.

**Comment by babyman** [comment]
It works very well for me and 15,000 other people, if it's not what you're looking for you can always uninstall it and find something that better meets your expectations.

Thank you for your opinion and good luck finding your ideal MRU tab switcher, there are numerous to choose from.
