### ISSUE TITLE
Shortcut key to open search

### ISSUE THREAD

**Issue by ScoreUnder** [babyman/quick-tabs-chrome-extension#133]
Currently, clicking the button on the toolbar opens the search popup. I would like to be able to bind this to a key.

**Comment by shidhincr** [comment]
It used to work previously; Not sure why it is broken now. May be chrome extension permission issue

**Comment by shidhincr** [comment]
Related to #129

**Comment by shidhincr** [comment]
Related to #123

**Comment by ScoreUnder** [comment]
I don't specifically have a problem with keyboard shortcuts not working, just not existing. The options menu lets me bind a "Close tab shortcur", a "Close all displayed tabs shortcut" and nothing else. I've looked on the chrome store page, the readme and the options page and I can't find any mention of a key to open the search popup.

**Comment by babyman** [comment]
You can update the keyboard shortcuts using the Chrome shortcut key management dialogue at the bottom of the Extensions page (chrome://extensions/):

![image](https://cloud.githubusercontent.com/assets/120736/15183631/dfaf3334-175f-11e6-93aa-276a5f5ad563.png)

For there you will see the keyboard shortcut setting for the extension:

![image](https://cloud.githubusercontent.com/assets/120736/15183648/f80a1a16-175f-11e6-94f2-df54742120f2.png)

As @shidhincr mentioned there is a bug in Chrome that prevents the keyboard shortcut opening the extension (#123) once you have opened the main (burger) Chrome menu, this might be a Mac only issue.

**Comment by KuroKensei** [comment]
Currently the default hotkey to open Quick Tabs search is 'Ctrl + q'.
As I had the same question; here's the current/up-to-date manual on how to set the keyboard shortcut for Quick Tabs
To open the extensions/hotkey menu in chrome nowadays;
1. right-click Quick-Tabs icon
2. select 'Manage extensions' 
3. click the 3 bars on the top left corner titled 'Extensions'
4. click 2nd from the top/last entry: "Keyboard shortcuts":
5. Look for/search extensions for 'Quick Tabs'

Have fun ^^
