### ISSUE TITLE
Closes almost all of the open tabs after a crush during search

### ISSUE THREAD

**Issue by juliancrg** [babyman/quick-tabs-chrome-extension#135]
Always when i'm typing "oned", exactly when I type 'd', it closes lots of tabs (from 5 to 10) and the counter of opened tabs gets crazy (from 30 jumps to 4) while there still remain more than 4 tabs opened. Its very dissapointing as some times they cannot be opened again with Ctrl-shift-T and finding them in the history is very difficult sometimes.

**Comment by babyman** [comment]
That's strange, is it possible that the "Close all displayed tabs shortcut" keyboard shortcut option has been mapped to 'd' rather than ctrl + shift + d?

![image](https://cloud.githubusercontent.com/assets/120736/15627279/f7db0582-24ac-11e6-95c9-108368b7606a.png)

**Comment by juliancrg** [comment]
I thought unchecking all checkboxes will disable it :facepalm . Thx, I think that unchecking them AND deleting the 'd' will do the job.

**Comment by vjpr** [comment]
I think there is a bug here. I have them all unchecked, and whenever I search in the box it closes all tabs.

![screen shot 2017-11-27 at 12 56 09 am](https://user-images.githubusercontent.com/281413/33245858-d1a24f2c-d30d-11e7-8abd-a242587016a5.png)
