### ISSUE TITLE
Cannot choose searched tab by arrow keys

### ISSUE THREAD

**Issue by jjlakis** [babyman/quick-tabs-chrome-extension#136]
Hi. It's a feature request.
I binded a shortcut in Chrome to open quick tabs because mouse is far away from my hand really often. But, when I hit the shortcut, then put the searching phrase, I can't choose interesting tab just by using arrow down key (there's still big distance to mouse).

**Comment by babyman** [comment]
@jjlakis that's strange, I too prefer the keyboard over the mouse.

The up and down arrow keys should allow you to navigate the list when it's open (this should be the case if you have searched or just popped the list open with the keyboard shortcut).  If you map keyboard shortcuts for the next/prev tab using the Chrome manage extensions page they should also allow you to navigate the tab list and even skip loading the popup if you wish.

When you hit enter it should take you to the currently selected tab and close the extension popup.

What OS and keyboard are you using?  The key codes I capture are 38 (up) and 40 (down).  I currently only use a Mac laptop so my testing starts and ends there.

Thanks,

Evan
