### ISSUE TITLE
Searching and selecting a tab with Enter opens a second tab containing the search string

### ISSUE THREAD

**Issue by babyman** [babyman/quick-tabs-chrome-extension#148]
Upon typing a search string into the extension's search bar, then selecting a tab by pressing the enter key, the extension brings focus to the active tab. But it also outputs a tab with the search string. 
- Reported by Andrew Teo via https://chrome.google.com/webstore/detail/quick-tabs/jnjfeinjfmenlddahdjdmgpbokiacbbb/reviews

**Comment by cybrbeth** [comment]
I'm having the same problem. Started for me sometime this calendar year.
OS X 10.11.6, Chrome version 58.0.3029.110 (64-bit)
Your product is super. Please fix this bug to make it extra-super. Thanks.

**Comment by Kejia** [comment]
the same issue on debian/ubuntu: 58.0.3029.110 (64-bit).

**Comment by MartinLichtblau** [comment]
Duplicate #183
