### ISSUE TITLE
Opening the popup in the center of the window

### ISSUE THREAD

**Issue by infokiller** [babyman/quick-tabs-chrome-extension#150]
Is there an option to configure the popup window to show up in the middle of the Chrome window?

Thanks!

**Comment by babyman** [comment]
Unfortunately Chrome manages the size and position of the popup window.

**Comment by infokiller** [comment]
Maybe it's not possible to do directly with the popup, but perhaps similar to how Vimium does it?
I know it's unlikely that it's in a high enough priority to be done, but I'd appreciate if you can consider it in the future, perhaps with relation to other features.

Thanks!
