### ISSUE TITLE
Allow keeping last search

### ISSUE THREAD

**Issue by MatanRubin** [babyman/quick-tabs-chrome-extension#157]
Each time you open quick-tabs the search is reset. It would be useful to add an option to keep the last search + results.
This is helpful if you have multiple tabs that match the search, and you're not sure which one you need - you want to quickly search the last thing you searched.
If that mode is enabled, the search term should be selected when opening quick tabs, such that when you start typing you replace the search term. This avoids having to select the search term to replace it.

BTW, this is the default behavior in Intellij searches.

**Comment by MeetM** [comment]
Implemented [here](https://github.com/babyman/quick-tabs-chrome-extension/pull/209)
