### ISSUE TITLE
just show the existing tabs and select without arrow keys

### ISSUE THREAD

**Issue by mperdikeas** [babyman/quick-tabs-chrome-extension#160]
Say I just want to quickly switch/focus to one of the existing open tabs. How do I see them? When I hit Ctrl+Q I see a list of URLs but it is not clear which of them correspond to the tabs I currently have open in my browser. So I have the following issues / questions:

1. Is there a way to show just the currently open tabs or at least display them prominently at the top of the list?
2. Is there a way to navigate that list without moving my fingers from the home row? I can use arrow up and arrow down to go through that list but those keys are not on the home-row or in the main keyboard block of keys and require too much movement.
3. Is there a way to focus back-and-forth between the current and the previously focused tab by pressing the same key? (e.g. what the back_and_forth command does in the i3 window manager).

By far my most frequent use case is to be able to switch/focus to one of my other *currently opened* tabs and this does not seem to be very well targeted / served (or I am missing something).

**Comment by babyman** [comment]
@mperdikeas, hopefully this helps;

1/. All tabs listed above the recently closed header are currently open in a browser window:

![in_action](https://cloud.githubusercontent.com/assets/120736/21958288/040f8a12-da79-11e6-84d0-c6b732d9af64.png)

2/. yes, if you map the previous and next tab keys using the "keyboard shortcuts" options linked at the foot of the extensions list page, in my case command K and J.

![image](https://cloud.githubusercontent.com/assets/120736/21958307/6aee9386-da79-11e6-92d0-26e172294c1f.png)

3/. with the previous and next tab keys mapped you can use them to switch between the 2 most recent tabs without even loading the popup window (from the docs):

> Chrome keyboard shortcuts (configured using the keyboard shortcuts dialog at the bottom of the Chrome Extensions page):
> 
> - Select previous tab without loading the popup window (unmapped by default)
> - Select next tab without loading the popup window (unmapped by default)
> - IMPORTANT the 'next tab' shortcut is only available for a second or so (while the badge text is orange) before the current tab is moved to the top of the MRU list.

Evan
