### ISSUE TITLE
Changing height of the box?

### ISSUE THREAD

**Issue by LeeSpork** [babyman/quick-tabs-chrome-extension#161]
I want to make the pop-up box cover more vertical screen-space so I can see more tabs at once, however I can't find a way to do this. After using CSS code to change the width by copying what was in the CSS box, I tried to change the height using:

body {
  height:500px;
}

However this did nothing. Anyone know a solution? Also having an option for this in the options page would be nice. Or maybe even making it resize by clicking and dragging like a window on a (computer) desktop?

**Comment by babyman** [comment]
Chrome constrains the window that contains the popup HTML, this includes it's maximum dimensions - http://stackoverflow.com/a/33459837
