### ISSUE TITLE
Switcher Window Shows up too small

### ISSUE THREAD

**Issue by q1c** [babyman/quick-tabs-chrome-extension#162]
![screen shot 2017-01-14 at 2 50 10 pm](https://cloud.githubusercontent.com/assets/4473048/21957643/ecfa9af2-da68-11e6-8076-61fe5a101747.png)

When I press Cmd+E, sometimes the extension shows up in appropriate size, but also it appears to be overly small in many other tiems.

**Comment by babyman** [comment]
Unfortunately this seems to be a bug in Chrome, see #91, please feel free to bring this to the developers attention as it's an old one :|
