### ISSUE TITLE
What is the actual shortcut to open the window?

### ISSUE THREAD

**Issue by Nowaker** [babyman/quick-tabs-chrome-extension#163]
I've tried hard to find it but it's nowhere to be found.

Not here:

![image](https://cloud.githubusercontent.com/assets/611746/22045497/e58ac490-dd1a-11e6-993c-36e737ece8e8.png)

Not here either:

![image](https://cloud.githubusercontent.com/assets/611746/22045523/1a21cbf4-dd1b-11e6-9fad-777b0576254d.png)

If there's a magical shortcut that triggers this window, it should be stated *somewhere*. Best if it's in plugin description.

**Comment by babyman** [comment]
@Nowaker,

Chrome has a central screen for managing shortcut keys on the extensions page:

![image](https://cloud.githubusercontent.com/assets/120736/22163398/abb6cf7c-df20-11e6-9534-950de670c688.png)

... once you click the "keyboard shortcuts" link at the bottom of that screen you should see something like this...

![image](https://cloud.githubusercontent.com/assets/120736/22163435/d0a272f0-df20-11e6-8343-4262f92e2018.png)

From there you can set the shortcuts, some will work better than others depending on your OS etc so some experimentation might be required.

Thanks for sticking with this =)

Evan

**Comment by Nowaker** [comment]
Wow. Thanks. Would never think of looking there. I propose that this be included in README.md. A brief explanation in plugin settings is worth making too. After all, JetBrains IDE users expect this to be available under a shortcut OOTB, otherwise it's not IntelliJ. :rofl:

**Comment by nkgm** [comment]
Well, there's this:
![image](https://cloud.githubusercontent.com/assets/5631881/23296081/2c7aaf18-fa7c-11e6-9c8a-851afe271f21.png)

And if you scroll to the bottom, there's this:
![image](https://cloud.githubusercontent.com/assets/5631881/23296128/54e80c52-fa7c-11e6-8d1d-4122dab65f94.png)

But I guess it's still a bit cryptic in that it doesn't state where to find the shortcut that will trigger the popup.

**Comment by Nowaker** [comment]
How about adding a direct link to chrome://extensions/?

**Comment by babyman** [comment]
Chrome ignores links like that, presumably for security reasons, I tried the technique mentioned here ( http://stackoverflow.com/questions/13125616/link-to-chrome-chrome-extensions-from-extension-options-page ) but it's not working...

**Comment by Nowaker** [comment]
It doesn't have to be a link. Stating chrome://extensions/ is still good enough. :)

**Comment by eromoe** [comment]
This tip is not too useful:
Important: This shortcut key is now managed by Chrome directly†.

It is better to write something like  
> go to chrome extension, scroll to the bottom and click `shortcut binding` to set a shortcut

PS: Forgive me , my system is Chinese, I don''t know the exact words used in Chrome

**Comment by eromoe** [comment]
OK, I found similar tip is write in the bottom.  Why not move to `Popup window shortcut`??
