### ISSUE TITLE
Wish animation can be turned off and pop-up can show up in center of window

### ISSUE THREAD

**Issue by spjspjspj** [babyman/quick-tabs-chrome-extension#164]
thx

**Comment by jgthms** [comment]
I agree with removing the animation. There's a lot of redrawing happening while it opens up, and it makes the extension feel slow, since you can't start using it instantly.

Ideally, the animation would be an option disabled by default.

**Comment by markwatson** [comment]
I don't believe the animation can be customized by chrome extensions, as per: https://stackoverflow.com/questions/43867226/is-it-possible-to-customize-my-chrome-extension-popup-windows-opening-animation?rq=1 

That being said, I'm just learning the chrome extension APIs now...

**Comment by babyman** [comment]
I imagine it's unlikely they will add support to the API, closing this in the meantime.
