### ISSUE TITLE
Search is finding terms individual letters in addition to word.

### ISSUE THREAD

**Issue by kalmdown** [babyman/quick-tabs-chrome-extension#167]
This tool is a lifesaver and I **love** it, but...it's returning useless results when searching individual letters instead of words.

In this case I am looking for "predix" and it is finding "pre" "edi" and "eed". This isn't any help.
![image](https://cloud.githubusercontent.com/assets/2244894/23684266/8ea79f14-0352-11e7-9a28-892774b8aefc.png)

**Comment by babyman** [comment]
@kalmdown with the latest code base you can switch between a number of search strategies.  I have added back fuzzy.js which I feel gives a solid set of result, if they are still too fuzzy regex or simple matching options are available too.

Evan
