### ISSUE TITLE
Quickly switch between last used tabs

### ISSUE THREAD

**Issue by haridsv** [babyman/quick-tabs-chrome-extension#17]
I see this extension filling the functionality offered by LastTab firefox extension. However one most used feature in that is the Ctrl+Tab to switch to the last used tab. I request adding that feature to this extension.

**Comment by danvk** [comment]
The list of tabs is in most-recently-used order, excluding the current one. So if you open Quick Tabs and hit enter, you'll go to your previous tab.

**Comment by babyman** [comment]
Thanks danvk
