### ISSUE TITLE
Since recently, the current tab is topmost on the list

### ISSUE THREAD

**Issue by utagger** [babyman/quick-tabs-chrome-extension#170]
It wasn't this way before. If I wanted to switch between tabs, all I had to do was hit CMD+E (mac) and enter. Now I need a down arrow too. I think it's less usable.
If this is because there were calls to show the current tab, then perhaps:

1. This could be a setting to choose, or
2. You could show the current tab only for info (the user wouldn't need to switch to the tab they're on, anyway), while the selected tab is the previous one.

Thanks! I love this extension.

**Comment by fede1024** [comment]
+1

**Comment by babyman** [comment]
Thanks for reporting this, I will take a look.

Evan

**Comment by peytonstafford** [comment]
+1
