### ISSUE TITLE
Request: be able to drag & drop tabs for rearranging

### ISSUE THREAD

**Issue by KeronCyst** [babyman/quick-tabs-chrome-extension#172]
This isn't exactly an issue, but I'm just wondering if left-click-holding on tabs in the extension's column to grab them for rearranging tabs might ever be implemented in the future. That would be a really cool feature!

**Comment by KeronCyst** [comment]
Wait, I'm still interested in this feature!

**Comment by babyman** [comment]
Cool, flagged it as a feature request, that will stop **stale bot** flagging it in the future =D

**Comment by NicoWeio** [comment]
Could you elaborate on how rearranging should work? Should it rearrange the actual tabs? I doubt this can be done consistently, as the extension aggregates tabs from all open windows.

**Comment by KeronCyst** [comment]
Yeah, the actual tabs was what I had in mind. Like, you'd drag-&-drop them throughout the vertical stack and they'd rearrange themselves in the default horizontal tab bar. I don't even know if this is possible, though!

**Comment by NicoWeio** [comment]
I am pretty sure this is possible with Chrome APIs. I've used extensions in the past, that could basically sort the tab list of a window. 
But still, I see no way this could work intuitively and consistently, given that you can search the list (which results in a different order than the actual tabs) and that multi-window needs to be supported. 
Anyway, if you have an idea how this could work _conceptually_, I'll be happy to try and implement it.

**Comment by KeronCyst** [comment]
Ah, that's true: I forgot about multiple windows. I guess this is not practically possible, then. Never mind; it's great as it is!
