### ISSUE TITLE
Simple expected behavior of Quick Tab

### ISSUE THREAD

**Issue by gh88** [babyman/quick-tabs-chrome-extension#182]
For Quick Tab I've assigned two keys: 
next tab = Ctrl+Q
previous tab = Crtl+Shft+Q.

When I press Ctrl+Q Quick Tab does nothing. What I expect from it is - it should switch to the next tab listed in the MRU list. And if I press it again, while keeping Crtl key depressed, it should go to the next tab and then to the next... It's exactly how Windows OS works, using MRU for process switching when you hit Alt+Tab hotkey. If you want to move in opposite direction in the MRU list, you just press Shift key. And that's how other applications work implementing MRU in tab switching. It's simple and it exactly how Quick Tab is expected to work too.

Could you please implement this simple and expected logic in Quick Tabs?

Thank you

**Comment by Wizek** [comment]
Maybe all you need to make it work exactly as you expect is switch over your shortcuts:

next tab = Ctrl+Shift+Q
previous tab = Crtl+Q

Could you try this and say if this solves your issue?
