### ISSUE TITLE
New empty tab is opened when pressing enter shortly after extension opens

### ISSUE THREAD

**Issue by fede1024** [babyman/quick-tabs-chrome-extension#183]
Sometimes I use quick tabs to switch between the two tabs I'm currently using. I map quick tabs to Ctrl-e and then do Ctrl-e + Enter to quickly switch between recent tabs.

I've recently noticed that sometimes, especially when done quickly, quick-tabs will actually open an empty tab. Can it be fixed? (maybe introduced in eb36bb34ad4f3c8c523).

Thanks!

**Comment by MartinLichtblau** [comment]
@jonasmellquist Even after reinstalling? How is that possible? I know why it happens when you change the related shortcut settings by removing the modifier keys.

**Comment by jonasmellquist** [comment]
Yes my bad. It's working as expected. I uninstalled it (Remove from Chrome) and installed it again, this time not touching the Quick Tab shortcuts..
