### ISSUE TITLE
Feature suggestion: use 'Delete' Key to close tabs

### ISSUE THREAD

**Issue by goleary** [babyman/quick-tabs-chrome-extension#186]
after opening the extension (`Ctrl + Q` for me) it would be cool if I could close the highlighted tab using the delete key (perhaps only if there are no characters to the right of the cursor to be deleted)

**Comment by DoctorGester** [comment]
Ctrl-D works, doesn't it?

**Comment by goleary** [comment]
ahh yes it does,should have read the features
