### ISSUE TITLE
Feature Request | Mute Tab

### ISSUE THREAD

**Issue by elig0n** [babyman/quick-tabs-chrome-extension#191]
Hello I really like this extension and hope you can add a mute tab button to the tabs list menu

**Comment by MartinLichtblau** [comment]
[Mutetab](https://chrome.google.com/webstore/detail/mutetab/acofndgbcimipbpeoplfjcapdbebbmca) does that already splendidly.

**Comment by szoper** [comment]
@MartinLichtblau Great, but it would be optimal to have muting/unmuting as additional tab action (like "close tab" already is). Sound-indicator icon would also be nice.  
That way, we wouldn't need two extensions to do the job :-)
