### ISSUE TITLE
Keyboard shortcut for opening popup in doesn't work in windows

### ISSUE THREAD

**Issue by ahmadalli** [babyman/quick-tabs-chrome-extension#196]
in windows `ctrl + e` searches google

![image](https://user-images.githubusercontent.com/2167301/32618201-459d8ec6-c58c-11e7-9a2c-91a1a88267d7.png)

and `ctrl + q` doesn't do anything.

**Comment by mbierman** [comment]
I can't get it to work on Mac either.

**Comment by jimocallaghan** [comment]
In the settings for QuickTabs it says `This shortcut key is now managed by Chrome directly†.` and further down it explains `† - shortcut keys managed by Chrome directly can be changed by scrolling all the way to the bottom of the chrome://extensions/ page and clicking "Keyboard shortcuts".`  I used this approach to change the pop open shortcut to ctrl-shift-i and it works well.

**Comment by BMorearty** [comment]
In Chrome on my Mac, when I visit chrome://extensions, there is no "Keyboard shortcuts" option on the  bottom of the page or anywhere else. I'm on Chrome 66.0.3359.139. Has it moved somewhere else? I have also searched Preferences and looked everywhere else I could think of.

Never mind, I just found it! Please update the configuration page to say: 

† - shortcut keys managed by Chrome directly can be changed by going to the chrome://extensions/ page, clicking the menu in the top left corner, and clicking "Keyboard shortcuts".

**Comment by babyman** [comment]
fixed in #224
