### ISSUE TITLE
a way to increase the vertical size of the popup?

### ISSUE THREAD

**Issue by leedoyle** [babyman/quick-tabs-chrome-extension#197]
Is there a way to increase the vertical size of the tabs list? 
I tried applying css like
```
body {
    height:1000px;
}
```
but it didn't work, sadly. For some reason only **width** works.

**Comment by JoelAzaria** [comment]
Confirming this in v2017.10.8.
Looks like a bug.  I tried overriding various containers from the extension's body on down and cannot increase the height.  I can *decrease* it (somewhere below 550px it starts shrinking iirc)

The extension `<body>` is inheriting `height:100%` from wherever instead of an absolute value. I'm guessing that's why it's constrained but not my strong suite.

**Comment by superclarkk** [comment]
This is also an issue for me.

**Comment by superclarkk** [comment]
I use this custom CSS to make Quick Tabs look good on a bigger monitor.  It could probably be improved, but I was unable to inspect the popup, and so had to use a bit of trial and error.  

~~~
body {
  width: 1000px;
}

.item {
  font-size: 130%;
  height: 40px;
}

div.tabimage img {
  margin: 8px 10px 10px 8px;
}

div.url {
  padding-top: 6px;
}
~~~

**Comment by JoelAzaria** [comment]
@superclarkk does this do anything to increase the height of the QT window?  Looking at the CSS I dont' think so (which is what the OP and I both want.)
BTW you can inspect the QT dropdown in Chrome's dev tools by showing the dropdown and right-click and choose 'inspect'.
That's how I came to conclusion that height is limited by an "upstream" container element.

**Comment by leedoyle** [comment]
@JoelAzaria  so this should be patched in chromium source code?

**Comment by JoelAzaria** [comment]
@leedoyle honestly I don't know.  I wouldn't *think* it's in Chromium but can't say.  My (barely educated) guess is that the "upstream" container is hardcoded somewhere in Quicktabs but someone who can read the code needs to verify that.

@babyman can you verify/debunk?
