### ISSUE TITLE
Delay in registering a new tab?

### ISSUE THREAD

**Issue by Overload119** [babyman/quick-tabs-chrome-extension#198]
Is there a minimum amount of time I have to be on a tab before it registers in the tab MRU history?
I'm noticing that the hotkey to go to my last tab does not always work, it redirects to the incorrect tab.

![out](https://user-images.githubusercontent.com/1012072/34309984-bdb8858e-e709-11e7-9cb6-365eb56fb855.gif)

**Comment by Overload119** [comment]
https://github.com/babyman/quick-tabs-chrome-extension/blob/db5a364e2ff7facc073bdd7edce05c991debda2a/quick-tabs/background.js#L401

I believe the answer is yes. Please make this configurable :)

**Comment by Wizek** [comment]
@Overload119 This may be somewhat related to this issue I raised at #203.

As in, AFAIU, that timeout is also used to try to keep context when someone uses a keyboard shortcut to navigate back and forth. Meaning that if I consecutively go back 3 tabs (taking less than 1500ms between each keypress), then only the last tab will be bumped into the front of my history.

So if we resolve #203 somehow, e.g. by detecting when ctrl is still pressed vs when it is released, we could reduce that timeout period to 0ms.

**Comment by babyman** [comment]
fixed in 8710ac4b299cfe2c2c4395c6e9a57a9c14278e52
