### ISSUE TITLE
[Feature Req] Refresh tabs

### ISSUE THREAD

**Issue by JoelAzaria** [babyman/quick-tabs-chrome-extension#202]
I would find it useful to have an option (right click, shortcut key for example) to refresh the tabs shown in quick-tabs' list.

Use case looks like this:
Doing web dev work on something like Joomla or WP.  Have multiple tabs open to pages that are behind a login.
Then either:

a) some time goes by and login times out or 
b) I save the session to return to it later (eg after a reboot or even in a few days)

now all those tabs have their destination url but are on a login screen,
I have to go to one of the tabs and login and then the I can refresh each of the others and they'll get to their intended page.  
These tabs are easy for me to find using quick-tabs' search (how I do it now.)  
If only I could just right click and do a refresh on the whole lot instead of manually activating each tab and F5 that would be awesome.

Thanks for considering.

Super extension btw, kudos dev(s).
Does what it says on the box and does it well so thank you very much for that.

**Comment by superclarkk** [comment]
Would this resolve your issue?

https://chrome.google.com/webstore/detail/reload-tabs/inhimoldpmckkeohhdkccpnpbpdfaple

**Comment by JoelAzaria** [comment]
Thanks @superclarkk.  Kind of sort of but not really.   What I really need is to refresh a subset not all open.  Just a few Quick Tabs so to speak.  Because refreshing 80 or more tabs at once would not make my computer happy I don't think.  
She cries under the load of fat-assed Chrome as it is (bloated memory-leaking sieve that it is...) I do not need to further kick her while she's down ;)

The other thing is they're not necessarily grouped in a same window.  More typically they'll just be the same domain/sub-domain.  I looked at the linked and some similar extensions, none quite tick all the boxes for me, plus, I think it's a great functional fit for QT and something that will attractive to that specific set of users who like me have tons of tabs and frequently get timed out of one site or another.
