### ISSUE TITLE
Can we make it work more similar to alt+tab / cmd+tab?

### ISSUE THREAD

**Issue by Wizek** [babyman/quick-tabs-chrome-extension#203]
For keyboard shortcut go back and forth, could we make it keep-pressing-based instead of timeout-based?

E.g. I set the go back shortcut to ctrl+1, and forward to ctrl+2. Now if I want to go back twice, I can press `ctrl-down, 1, 1`. But the thing is, if I wait even 2 seconds between `ctrl-down, 1, pause, 1`, then instead of going back twice, I end up where I started. Could we somehow detect that ctrl is still pressed? To make it work quite similarly to how alt+tab works on Windows and cmd+tab works on macOS?

I guess if no other way, a contentscript could check for ctrl key position.
Or any other ideas?
Any thoughts on the above?

**Comment by JoelAzaria** [comment]
Unless I'm misunderstanding @Wizek isn't what you want basically ctrl+tab and ctrl+shift+tab built into Windows OS? (not sure Mac/Linux equivs)

**Comment by MartinLichtblau** [comment]
@Wizek I think the only way to make switching more intuitive is to show a GUI with tab snapshots to step through; as mentioned in #247.
