### ISSUE TITLE
Examples of how to use various search types

### ISSUE THREAD

**Issue by superclarkk** [babyman/quick-tabs-chrome-extension#204]
Great extension, btw!

It would be useful to have some examples of how to use the various search types, including how to pass options to them to change their behaviour, and what the difference is between them and their benefits.

For instance, personally, I'd like a way to include and exclude search terms, but have no idea if it's possible with any of the search types:

The words "Jack" AND "Jill" in any order (exclude pages that don't include them both)
The word "Jack" but NOT "Jill" in any order

**Comment by MartinLichtblau** [comment]
If you want to exclude terms you should use regex. But it all other cases use one of the other search-types, best fuse.

**Comment by superclarkk** [comment]
I'd appreciate an actual answer to this before it's closed.  I asked for examples.
