### ISSUE TITLE
Shortcuts Bug

### ISSUE THREAD

**Issue by supersaiyansubtlety** [babyman/quick-tabs-chrome-extension#208]
For any of the shortcuts controlled via Quick Tabs' options page; disabling all of the shortcut's modifier keys causes the shortcut to trigger on just the configured character. Additionally, if no character is configured for the shortcut, any character will trigger the shortcut. 
I un-selected all modifier keys and deleted all triggering characters, expecting this to disable the shortcuts. Next time I tried to search for a tab, all tabs in all windows were closed except for the current tab. 
For now I've just selected all modifier keys and chosen less-used characters, but having no modifier keys or no character should really disable a shortcut.

**Comment by MartinLichtblau** [comment]
Same as #220

**Comment by jamesshannon** [comment]
+1 I just ran into this and it was very... disruptive.

I also ended up selecting all modifier keys, but it took me a while to realize why all my tabs were closing as soon as I typed 'd' into the search box.
