### ISSUE TITLE
kb shortcut cntrl+enter not working as expected - new tab created with just search string, not searchengine+searchstring

### ISSUE THREAD

**Issue by Presareo** [babyman/quick-tabs-chrome-extension#216]
To reproduce, using default install settings

1) Activate extension
2) Type searchstring
3) Hit cntrl+enter

What you should see: new tab with URL https://www.google.com/?search=searchstring

What happens on my system: new tab with URL searchstring/

Any system / chrome configuration that is known to cause this type of behavior?

**Comment by JohnnRen** [comment]
+1 on Chrome 68 (Is this the expected behavior?)
