### ISSUE TITLE
Could newly opened tabs be not placed at the front of the list to avoid confusing keyboard shortcut behavior?

### ISSUE THREAD

**Issue by Wizek** [babyman/quick-tabs-chrome-extension#219]
I use ctrl+1 and ctrl+2 to navigate back and forth between recently opened tabs. It works great most of the time, I use it often.

However, when I open many tabs at once, (e.g. middle clicking 5 google search results) suddenly these shortcuts become confusing and useless: ctrl+1 takes me to a page that I've never visited yet, and often I get quite lost: "Why doesn't this take me back to the page I __did__ focus last?"

Two proposed solution ideas:

1. Only put tabs in the list that I actually did focus! That way it's never confusing.
1. Or maybe we can still put them at the end of the list of open tabs if that makes it easier for search to still work as expected, and make the keyboard bindings still work too without confusion.

I'm okay if this is just an option in the settings, but making it default might make sense too.

What do you think, @babyman?

**Comment by MartinLichtblau** [comment]
I like your options, but didn't wanna think about the details first. Now I implemented it like your option 2. You are welcome to download and try-out the PR to test for Errors.
