### ISSUE TITLE
Accidentally closing all tabs

### ISSUE THREAD

**Issue by henrikba** [babyman/quick-tabs-chrome-extension#220]
I found a pretty nasty issue where I open the dialog, search, tap arrow down to select; at which moment **ALL** my tabs would be closed. Happened a few times before I understood.

To reproduce;
* configure "Close all displayed tabs shortcut" as nothing (no ctrl/shift/alt, and empty text box in the end) (I did this as I was afraid accidentally hitting this and losing all my open tabs)
* open dialog
* tap arrow down (or likely; *any* key) -> all tabs close.

Think I even saw a negative comment in the user feedback (chrome web store) on this. 

Is there a way to disable the keyboard shortcut to close all tabs?

**Comment by 0xC0FFEE** [comment]
Exactly this happend to me too. Except that I hit the *space* key, which then closed all tabs.

To workaround this I did configure "Close all displayed tabs shortcut" to require all special keys and some bogus key, which I'll never hit.

So a way to disable this (or all) keyboard shortcuts would be nice.

**Comment by MartinLichtblau** [comment]
Me too. I thought unchecking would deactivate the function all together. BUT, now we know :-D

**Comment by MartinLichtblau** [comment]
#148 #183 #208  All issues are related to same lines of code.
