### ISSUE TITLE
THIS EXTENSION HAS BEEN COMPROMISED & INFECTED WITH VIRUS!!!

### ISSUE THREAD

**Issue by andyhu** [babyman/quick-tabs-chrome-extension#221]
I've recently noticed that with the Chrome Web Store version of this extension installed, it constantly seek to modify the content of the Javascript files on nearly any websites you visit. It injects a suspicious js file from fjlqqc.om. I've found the malware is hidden in the jquery-3.2.1.min.js file. The version from Github is not affected, just the Chrome Web Store version.
I'm not sure if this is done by the author of this extension on purpose or he's ID had been hacked, but in any cases please stop using the online version immediately and if convenient try to report it to Google(after uninstalling it).
**How to test it:**

- Install the online version of this plugin: https://chrome.google.com/webstore/detail/quick-tabs/jnjfeinjfmenlddahdjdmgpbokiacbbb and enable it.
- Visit http://youmightnotneedjquery.com/
- Open Chrome Developer Tools panel and check the source code of http://youmightnotneedjquery.com/js/prism.js. Please inspect it on the Chrome Developer Tools' Sources panel.
- Try to search for fjlqqc.om in the source code.
- Disable the plugin and do it again to prove this extension is responsible for all the tricks.

**Comment by JoelAzaria** [comment]
1.  I do not understand what the "infection" is.  You are claiming a virus but you are not explaining what virus it is, what it does, what exact infection is...  You list some files but I don't know that this is a virus or not.
2.  Running uMatrix as I always do I do not even get prism.js.  If I turn uMatrix off, I get prism.js but that string is not in it.

So please explain wth this is all about and show some proof of infection you claim (from a virus scanner preferably.  Like VT or Jotti at least, as an example)

**Comment by babyman** [comment]
I'm not sure what's going on with your computer there mate but the jquery library used in the plugin is the one here in github, the last update date in the Web Store matches the version number deployed and I don't see any mention of fjlqqc.om in the prism.js you link to in the ticket or the one linked to by the website.

I'm going to close this unless you can post something a bit more conclusive.  I might suggest you do a full virus scan of your computer though...

Thanks
