### ISSUE TITLE
Feature request: Add an option to change the delay time to register the most recent tab.

### ISSUE THREAD

**Issue by contentfree** [babyman/quick-tabs-chrome-extension#233]
When using the keyboard command to return to the most-recent tab, you have to wait a short amount of time (it seems about two seconds) before the extension records the current tab as the new most recent tab. 

It works great most of the time. However, it'd be nice to be able to configure that delay.

**Comment by contentfree** [comment]
It's currently hardcoded to `1500` milliseconds at https://github.com/babyman/quick-tabs-chrome-extension/blob/master/quick-tabs/background.js#L401

**Comment by MartinLichtblau** [comment]
Certainly needs to be configurable!

**Comment by babyman** [comment]
fixed in 8710ac4b299cfe2c2c4395c6e9a57a9c14278e52
