### ISSUE TITLE
Documentation missing shortcut list

### ISSUE THREAD

**Issue by sheam** [babyman/quick-tabs-chrome-extension#234]
The documentation doesn't seem to state which keystroke opens the tab list.
All I want is it swtich between last-used tabs, similar to alt-tab in windows or cmd-tab on mac... is that possible?

**Comment by babyman** [comment]
Hi @sheam,

You can, the documentation needs updating but you can manage the keyboard shortcuts from the Extensions > Keyboard shortcuts page in Chrome;

I have mine set like this:

![image](https://user-images.githubusercontent.com/120736/49018249-ee2ad280-f158-11e8-9bed-0ef148765813.png)

Just be aware that "next tab" is only available for a second or so (while the tab count is orange) before the extension updates its tab order.

**Comment by sheam** [comment]
Ahh, I see now.
