### ISSUE TITLE
Is it possible to add new Search Type like Chrome Address bar search?

### ISSUE THREAD

**Issue by spjspjspj** [babyman/quick-tabs-chrome-extension#237]
On chrome address bar, I can type multiple words and find results that match all of them:

![image](https://user-images.githubusercontent.com/22482923/49827769-1b31d480-fd58-11e8-9128-506f05f8400b.png)

I really like this way of searching.

The closest in Quick Tabs is regex search but it's different in that:
1. `.*` must be used
2. order is not arbitrary

**Comment by MartinLichtblau** [comment]
That's how I would expect it to search!?
