### ISSUE TITLE
Quick Tabs is not quick, actually is Slow, with multi-stage menu drawing, slower than Saka

### ISSUE THREAD

**Issue by Yzrsah** [babyman/quick-tabs-chrome-extension#238]
When opening the Quick Tabs menu, you can see the multiple stages of drawing while building-up the menu:
- Search bar pops up with empty tab list
- Menu re-adjusts size and shifts to the left
- Tabs results appear

I consider this to be low quality.

I use a different extension called ["Saka"](https://chrome.google.com/webstore/detail/saka/nbdfpcokndmapcollfpjdpjlabnibjdi) which pops up instantly, and does not have a delay.

**Comment by babyman** [comment]
Thanks for your comment, pull requests are always welcome.

**Comment by JoelAzaria** [comment]
fwiw I do not experience this slowness.  Quick tabs is pretty quick.  I typically have around 50 tabs open (which runs along the edge of Chrome getting unstable for me) and QT works fine.  With a bunch of custom CSS.
Maybe it's another extension you're running @Yzrsah

**Comment by Yzrsah** [comment]
@JoelAzaria No, the UI is slow on all computers, even with 0 other extensions

It has nothing to do with me personally or anything on my computer

**Comment by Yzrsah** [comment]
@JoelAzaria 

No, the UI is slow on all computers, even with 0 extensions installed. It has nothing to do with me personally or anything on my setup.

Some people don't really notice the details in things like this and cannot perceive latency or precise time. For example, they will click the button on their own computer and the UI will take 250ms to render, then directly after that they'll post to you on GitHub to say it's "pretty fast" and wonder if caused by Maybe-it's-another-extension-you're-running

Try recording a video of it and count the number of frames.

**Comment by Yzrsah** [comment]
@JoelAzaria 

No, the UI is slow on all computers, even with 0 extensions installed. It has nothing to do with me personally or anything on my setup.

Some people don't really notice the details in things like this and cannot perceive latency or precise time. For example, they will click the button on their own computer and the UI will take 250ms to render, then directly after that they'll post to you on GitHub to say it's "pretty fast" and wonder if it's caused by Maybe-it's-another-extension-you're-running

Try recording a video of it and count the number of frames and post that number. If you want to be realistic about "Maybe it's another extension you're running"

**Comment by Yzrsah** [comment]
@JoelAzaria 

No, the UI is slow on all computers, even with 0 extensions installed. It has nothing to do with me personally or anything on my setup.

Some people don't really notice the details in things like this and cannot perceive latency or precise time. For example, they will click the button on their own computer and the UI will take 250ms to render, then directly after that they'll post to you on GitHub to say it's "pretty fast" and wonder if it's caused by Maybe-it's-another-extension-you're-running

Try recording a video of it and count the number of frames and post that number - if you want to be realistic about "Maybe it's another extension you're running"

**Comment by Yzrsah** [comment]
@JoelAzaria 

No, the UI is slow on all computers, even with 0 extensions installed. It has nothing to do with me personally or anything on my setup.

Some people don't really notice the details in things like this and cannot perceive latency or precise time. For example, they will typically click a button on their own computer and the UI will take 200ms to render, then directly after that they'll post to you on GitHub to say it's "pretty fast" and wonder if it's caused by Maybe-it's-another-extension-you're-running

Try recording a video of it and count the number of frames and post that number - if you want to be realistic about "Maybe it's another extension you're running"

**Comment by JoelAzaria** [comment]
@Yzrsah Don't make assumptions about my ability to perceive or not perceive.   QT opens and renders as fast as any other extension I've used or use and I have no problems with it's time to open or rendering.  If you want to post videos showing YOUR issues to show that YOU have a problem, please do.  Otherwise, I made a suggestion.  Do with it what you will. 

Project maintainer has suggested a PR is welcomed.
