### ISSUE TITLE
how does Quick Tabs retrieve favicons?

### ISSUE THREAD

**Issue by shiftyshady** [babyman/quick-tabs-chrome-extension#240]
First of all, thanks for this great extension.
I have seen another extension that uses a Google service to download favicons thus sending your session data to Google.
I see there is an option to disable favicons, so I am wondering if I should.

**Comment by babyman** [comment]
Thanks @shiftyshady, the extension links to the tab sites favicon directly so it should be safe in that sense, you can see the code if you inspect the popup html:

![image](https://user-images.githubusercontent.com/120736/50806920-b7eb8180-12c6-11e9-8c75-f0953326d2e9.png)

Hope that helps,

Evan
