### ISSUE TITLE
Options page confusing

### ISSUE THREAD

**Issue by MartinLichtblau** [babyman/quick-tabs-chrome-extension#249]

**Comment by tothferi** [comment]
Greate expension, but recently I had 2 problems. I noticed that whenever I search for something and then I go to that tab(hit enter) a separate tab opens as well with a google search with the same phrase.  And I was searching on the options page about 20-30 minutes to figure out what causes this. But I could not find it, so I just left the problem as it is.
Then I have noticed than when I hit "d", even inside a search string it deletes one of my tabs.
So I went to the options page again and I found this line: "Close tab shortcut:* ...". And then I found the line below too: "Create a new tab with the search string as URL:* ..."
My point is that these 2 lines, especially the 2nd are so misleading. Usually people don't consider something set (like now a keyboard shortcut) without explicitly clicking a field that it is set.
Also, if I want not to have the second shortcut, I have to check all the boxes inside (so it will become an extremely rare shortcut), which is an ugly solution.
I suggest to have a checkbox weather this shortcut should be set or not.
