### ISSUE TITLE
Switching to a tab resizes the browser window

### ISSUE THREAD

**Issue by wolverian** [babyman/quick-tabs-chrome-extension#25]
When switching to another tab, if the window is currently maximized, its dimensions change to its last non-maximized size. The maximize/restore button does not change, though, i.e. the window looks non-maximized but the button shows "restore", not "maximize", and you have to press it twice to maximize the window back. Chrome 6.0.472.55 on Windows 7 64-bit.

**Comment by babyman** [comment]
Pretty sure this is not an issue any longer
