### ISSUE TITLE
Suppress "Recently Closed" tabs?

### ISSUE THREAD

**Issue by alon91** [babyman/quick-tabs-chrome-extension#254]
I personally never want to reopen Recently Closed tabs using Quick Tabs -- I only want to select from open tabs and bookmarks.

Is there a way to suppress the "Recently Closed" tabs section? Alternatively can I request a feature to suppress that section in settings?

**Comment by babyman** [comment]
On the options page you can set the Closed tabs list size to none.

![image](https://user-images.githubusercontent.com/120736/53539065-13bfd300-3ade-11e9-83bc-3c9dde9092a0.png)
