### ISSUE TITLE
"Substring Search" that searches for individual words?

### ISSUE THREAD

**Issue by alon91** [babyman/quick-tabs-chrome-extension#255]
"Substring Search" mode come closest to working for me, but fails a personal critical use case:  searching on multiple substrings, each separated by space. An illustration:

- Sample tab or bookmark name: **Account Health Report (AHR) notes + links**
- Substrings I'd like Quick Tabs to match: `ahr notes` or`notes ahr`
- Substring that must currently be used to match: `ahr) notes`

Note that other search types may work, but I find that they return too many responses or are more sophisticated than what I'm looking for.

This is the one feature that blocks me from using Quick Tabs which otherwise looks like an incredibly powerful extension. I'm currently using [Popup My Bookmarks](https://github.com/foray1010/Popup-my-Bookmarks) 50+ times a day. Search results are great but PMB doesn't support open tabs and has a few other small-to-medium challenges. Would love to switch to QT but search results are a blocker at the moment.

Happy to provide more details, examples, etc. Many thanks in advance!!

**Comment by MartinLichtblau** [comment]
Have you tried the word-based Fuse search?
