### ISSUE TITLE
Shortcuts stopped working

### ISSUE THREAD

**Issue by rb-109** [babyman/quick-tabs-chrome-extension#257]
Hi, I recently noticed that shortcuts stopped working
I am using Chrome 72.0.3626.121
I checked for conflicts with other extensions and tried changing the hotkeys (I particularly use the Previous Tab a lot), but I can't get any of the them to work, including CRTL + E to activate.
Seems to be since the last Chrome update.
Am I the only one or did Chrome's latest release break something here?

**Comment by seslash** [comment]
It looks like since the last release, the behaviour of the hotkeys was reversed: https://github.com/babyman/quick-tabs-chrome-extension/blame/2917b59c9165cf89cd9bf2c2b2ddbe2e82408c54/quick-tabs/popup.js#L528-L532

Switch hotkeys for "Switch to Newer tab" and "Switch to Older tab".

**Comment by chipbite** [comment]
I cannot open search popup using any keyboard shortcut.
I also cannot find where they are set, using the help text provided (bottom of extensionspage).

Tips?

**Comment by MartinLichtblau** [comment]
@rb-109 @seslash Indeed, the mapping changed. Did you try setting new ones and it still doesn't work? 
Try using a combination of Shift + Alt.

**Comment by seslash** [comment]
@MartinLichtblau changing key mapping worked for me.

**Comment by MartinLichtblau** [comment]
Great! So this closes #257
