### ISSUE TITLE
Tabs popup window height

### ISSUE THREAD

**Issue by rimvydukas** [babyman/quick-tabs-chrome-extension#259]
Hi,
How can I set popup window height? I've tried via css in options but it seems that plugin does react to height: css option :(

**Comment by MartinLichtblau** [comment]
Remember that a popup can't exceed the maximum dimension of 600 in height and 800 in width.

**Comment by rimvydukas** [comment]
> Remember that a popup can't exceed the maximum dimension of 600 in height and 800 in width.

Any why is that? Is there any particular reason for this?

**Comment by MartinLichtblau** [comment]
That's the rule in Chrome. But I don't know why Google/Chrome or Chromium did that.
