### ISSUE TITLE
Open link in new tab

### ISSUE THREAD

**Issue by wuffo** [babyman/quick-tabs-chrome-extension#260]
Right click to open a link in a new tab used to put that tab at the top of the list. Now it puts it at the very bottom. Not sure if this is a bug or a feature, but I prefer the previous behavior.

**Comment by MartinLichtblau** [comment]
Right clicking on a link opens it in a foreground tab, i.e. focuses the newly opened tab, right? 
If that's the case, the mentioned behavior is unexpected, since by design only background tabs are put at the end of the list, because you haven't visited them yet.
