### ISSUE TITLE
sometimes stops letting me switch to window with tab

### ISSUE THREAD

**Issue by jwuuu** [babyman/quick-tabs-chrome-extension#261]
This goes away when I reload Chrome, but then it comes back later (possibly after hibernating my laptop and waking up again?)... 

Sometimes I click the icon, type in the tab I'm looking for, find the tab, and hit enter, and the focus doesn't change to this tab.

**Comment by MartinLichtblau** [comment]
Is it similar to issue #232 ?

**Comment by leonstevens** [comment]
I have this issue too. If I disable/re-enable the extension, it corrects the issue, but it comes back again later.

**Comment by MartinLichtblau** [comment]
@jwuuu @leonstevens  are you using Linux and if so, does the issue #232 sound familiar?

**Comment by leonstevens** [comment]
I'm on a Chromebook....yes, it's similar....
