### ISSUE TITLE
Close tab closes dropdown

### ISSUE THREAD

**Issue by Briqq** [babyman/quick-tabs-chrome-extension#265]
Quick Tabs is a great way to close down tabs you no longer need. The process is tedious though, because closing a tab, whether by mouse or keyboard shortcut, closes the dropdown, which you then need to reopen and potentially need to re-scroll to correct place.

Would be great if close tab didn't close the app.

**Comment by MartinLichtblau** [comment]
@Briqq This can be done.
But out of interest: why use these shortcuts, when you could just switch to the tab and close it with chromes integrated shortcut? Then you would also see it and confirm whether it's the right one and you really wanna close it.

**Comment by Briqq** [comment]
@MartinLichtblau Let's say I have 40 open tabs. I want to prune them. Quick Tabs is a great solution in that it allows me to see what I have open, and close the tabs I no longer need.

But having to reopen Quick Tabs for each instance makes this much less efficient.

**Comment by MartinLichtblau** [comment]
Ok, will be done.
