### ISSUE TITLE
I am using with Opera

### ISSUE THREAD

**Issue by bendy101** [babyman/quick-tabs-chrome-extension#266]
I am using Opera browser (recently discovered it blows chrome out of the water). Sometimes the hotkeys stop working and I have to click the extension icon and then they work again. 

Opera is Chromium based and runs Chrome extensions....

If you could test it on an Opera browser that would be fantastic

**Comment by MartinLichtblau** [comment]
Welcome @bendy101 
1. can you rule out that it's not some other extension intefering with it?
2. can you give us an error, e.g. by activating error logging for the extension?
3. How often and when does it happen?
