### ISSUE TITLE
What is the app's keyboard shortcut on Chrome OS?

### ISSUE THREAD

**Issue by hourback** [babyman/quick-tabs-chrome-extension#267]
How do I find out what the app's keyboard shortcut is on Chrome OS?

I'm still new to Chrome OS so I'm still finding my way around.  But I can't find out a way to determine any keyboard shortcuts that are specific to Chrome extensions; it seems like they are all managed through Chrome OS's keyboard shortcut settings.

Thank you for such an awesome extension!

**Comment by lindeloev** [comment]
I don't know Chrome OS, but the last reply here solves it for the Chrome browser: https://github.com/babyman/quick-tabs-chrome-extension/issues/133#issuecomment-423676595
