### ISSUE TITLE
Option to allow disable searching history

### ISSUE THREAD

**Issue by kflu** [babyman/quick-tabs-chrome-extension#268]
Showing result of your browsing history can be embarrassing. And I don't find it useful for searching through history (at least for my use case). So it'd be better to have an option to allow disable or exclude searching of browsing history.

**Comment by MartinLichtblau** [comment]
@kflu You mean the recently closed tabs, do you? Since QT doesn't show your history. 
So, just **set the option Closed tabs list size: to none.**

**Comment by babyman** [comment]
@kflu QT will search your history but only if you start or end you search string with 3 spaces, it won't 'fail over' to a history search when other searches return zero results.  Recently closed tabs can be excluded as per @MartinLichtblau comment.
