### ISSUE TITLE
Jumping doesn't work with tabs suspended by Great Suspender

### ISSUE THREAD

**Issue by trevorh** [babyman/quick-tabs-chrome-extension#271]
Hi,

I have the Great Suspender installed which suspends tabs and changes their URL to something like: `chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#ttl=Loan%20pre-qu`.

Selecting these tabs in QT doesn't result in a jump. Also, when these tabs are reloaded so that their location changes to their non-suspended URL, QT's list doesn't update.

Jumping to tabs that are not suspended works as expected.

Happy to provide more detailed logging - here's a [video](https://www.screencast.com/t/xdgq9noZoMTK) of this behavior

Best,
Trevor

**Comment by MartinLichtblau** [comment]
I've experienced it too. Did you activate the option "Apply Chrome's built-in memory-saving when suspending"? If so deactivea it ‒ the Chrome feature itself is buggy.

**Comment by trevorh** [comment]
Ah, fantastic - thanks for the tip. It took a browser restart but QT is jumping again. :)

**Comment by webziggy** [comment]
+1 from me - I have the same set up - QT and Great Suspender(GS). I had the ticked the 'Apply Chrome's built-in memory-saving' feature in GS as it suggested it'd save even more memory. Then I ran into the problem, searched the issues here and found this. 
So maybe you should consider highlighting the compatibility issue on the QT options pane?
