### ISSUE TITLE
Option to focus content instead of url on switch 

### ISSUE THREAD

**Issue by alexg9010** [babyman/quick-tabs-chrome-extension#272]
Hi, 

First of all thanks for this very nice plugin, I just recently started using it to reduce my hands-on-mouse time and this really helps. 

I have this one small issue that keeps annoying me, basically upon switching to my tab of interest I always land at chromes url or search bar, such that I have to click with the mouse or hit tab a couple of times to reach the actual website. 
This is pretty frustrating on github when I am already half way through reading a manual, then switching to some other tab and switching back, then I am at the search bar and after hitting tab he offers me to 'skip to content' when I hit tab, but has already scrolled back to the beginning of the website.

I don't know how easy it would be to fix this, but it would nice to have an option that allows to directly jump to the content instead of url-bar.

Best, Alex

**Comment by mbhutton** [comment]
@alexg9010 Are you on macOS by any chance? 

I'm seeing a very similar bug on macOS only. After correctly switching to the correct tab (e.g. tab 3), then keyboard focus is always put on the tab widget of tab 1 (by "tab widget" I mean the UI element drawn on top of the page content - the UI element which you click to change tabs).

I use 2 different plugins which do tab switching (WorkFindy Plus and Quick Tabs), and both of them have this issue on macOS, while both of them work fine on both Windows and Linux (with the latest version of Chrome).

**Comment by alexg9010** [comment]
Hi @mbhutton, 
yes I am running macOS 10.12. This is similar for me, upon switching to the right tab the url bar is activated.

**Comment by michalbrz** [comment]
I have the same problem on mac. Currently the only option to navigate is to press "Tab" and then use spaces to go down, which is ok unless you were in the middle of the page - "Tab" takes you to the top. If anyone has better workaround I'd be happy to hear it.

**Comment by babyman** [comment]
This issue sounds like it's related to #273 which I fixed a couple of days ago, please reopen this ticket if I'm wrong.

Evan
