### ISSUE TITLE
Tab count stops counting down 

### ISSUE THREAD

**Issue by kludgefactory** [babyman/quick-tabs-chrome-extension#275]
At some point while using chrome, the tab count in the extension badge stops counting down when closing tabs but does increment when opening tabs. 

Toggling the extension on and off resolves the issue temporarily. I haven't noticed a pattern for when the count stops decrementing

**Comment by jgfaust** [comment]
Does opening the menu stop happening at the same time?

**Comment by Spetnik** [comment]
@jgfaust I have this issue and yes, it does. Disabling and re-enabling the extension solves the issue but it comes back eventually.

**Comment by kludgefactory** [comment]
> Does the tab list menu stop functioning when this occurs?

Anecdotally, yes. But I wasn't paying attention enough to say for sure that both issues always happened together.

**Comment by kalpaj12** [comment]
This doesn't just affect the tab count, the closed tab's entry (i.e. URL and the favicon) still exists in the popup.

**Comment by NicoWeio** [comment]
I hacked away what might me a pragmatic "fix". It filters for valid tabs right before executing the search.

```javascript
function checkTabs(tabs) {
    return tabs.filter(tab => (tab && tab.title));
}
```

https://github.com/babyman/quick-tabs-chrome-extension/commit/ca3913e2d1a3736ccb24c4ac41d29be50ebd747c

I don't know if that actually prevents the error, but I think it should. ¯\_(ツ)_/¯
