### ISSUE TITLE
[Bug] Cycling through Tabs using shortcut keys doesn't work on "tabs outliner" "tabli" or similar window(FRAMELESS window).

### ISSUE THREAD

**Issue by kissglay** [babyman/quick-tabs-chrome-extension#277]
Cycling through Tabs using shortcut keys doesn't work on "tabs outliner" "tabli" or similar window that opened by an extension, so when you cycled to these windows, cycling shortcut keys stop working, and you are kinda stuck in these windows.
This situation starting from several release back, and it didn't occur before that.

**Comment by kissglay** [comment]
Cycling through tabs using shortcuts is practically unusable with this bug present and it seems nobody cares about it. Install an extension called "quickey" to circumvent the issue.

**Comment by babyman** [comment]
@kissglay I think I finally understand the issue you are describing, if you move focus to one of these frameless windows is it the quick next/prev tab keys that stop working? Or the Quick Tabs popup shortcut? or both?

Thanks for your persistence with this, I will try to take a look at the issue this weekend.

Evan

**Comment by kissglay** [comment]
Thanks for pay attention to this issue.
For example: I'm using "Tabs Outliner" extension. When I switch to it (it has a seperate frameless window listing all the tabs in tree style), and wait till the "Quick tabs" icon color changes to normal, both shortcuts keys and popup window stop working.
But if you switch to this frameless window and press the quick next/prev tab keys while the "Quick tabs" icon still orange, shortcut keys still work at least.

**Comment by babyman** [comment]
@kissglay I pushed an update to Quick Tabs last night, please let me know if it fixes this issue.

Thanks

**Comment by kissglay** [comment]
@babyman Yes, it's been fixed. Thank you.
