### ISSUE TITLE
QuickTabs No Longer Sorting/Displaying By Most Recently Used Tabs

### ISSUE THREAD

**Issue by rmanzt** [babyman/quick-tabs-chrome-extension#281]
Quicktabs used to display tabs by those most recently used in chrome.

It stopped doing this a while ago.

Is there a way to make it do this again?

**Comment by babyman** [comment]
That's very strange, it should always show them in MRU order unless you have typed a search query, restarted Chrome or the extension (this includes if the extension updates to a new version).

I would love to have some more details about your system, config, etc to dig into why this would happen...
