### ISSUE TITLE
Enabling Quick Tabs causes Chrome freeze on weaker machines

### ISSUE THREAD

**Issue by will-ca** [babyman/quick-tabs-chrome-extension#282]
On an account with a bit over ten thousand bookmarks, simply launching Chrome with Quick Tabs enabled will cause all my weaker machines to freeze with 100% CPU usage after half a minute or so.

This behaviour occurs even when no user interaction with the Quick Tabs widget occurs, and it occurs regardless of whether automatic bookmark and history searching is disabled.

**Comment by MartinLichtblau** [comment]
Then, how do you know it's Quicktabs fault?

**Comment by will-ca** [comment]
@MartinLichtblau I spent probably half an hour rebooting my computer(s), and trying different combinations of extensions and configurations, and the the only ones that produced this freeze were the ones with Quick Tabs open.

Additionally, I've since switched to QuicKey, and I've not encountered this freeze despite every other aspect of my Chrome configuration having been unchanged.

**Comment by MartinLichtblau** [comment]
Wow, how many bookmarks do you have? And what happen if you enable only Quicktabs, does startup still take so long? I guess you already re-installed Quicktabs to see if such a reset solves it.

Apart from that, soon there'll be a new Quicktabs version that opens faster than any other extension. Right now it's ~300ms, then it's ~50ms. And an option to en/disable bookmarks and history is overdue anyway.
