### ISSUE TITLE
Swap Last Used Tab

### ISSUE THREAD

**Issue by impguard** [babyman/quick-tabs-chrome-extension#283]
There are two hotkey options for moving forward and backward in my tab search history. What would be useful is a vim-like option of swapping back and forth between my most recently two used tabs.

i.e. I'm on Tab A and I use quick tabs to jump to Tab B. I can press my hotkey to swap back to Tab A. Using it again swaps to Tab B. If I spam my hotkey, I will continue to swap back and forth between Tab A and Tab B.

Quite a useful hotkey when one is editing a Google Doc on one tab and referencing a few other tabs constantly.

Thanks!

**Comment by nanobrad** [comment]
Isn't this already available through the "Switch to Older tab" shortcut that you can assign in Chrome? It works like the Alt-Tab in Windows going through tabs in a most recently used order. If you pause, then it resets so it will effectively toggle.

**Comment by impguard** [comment]
I don't believe that exists. There are extensions for this, but seems unnecessary imo.

**Comment by MartinLichtblau** [comment]
You have a shortcut for going back and forth in history, i.e. selecting the most- or least recent tab.
To switch back and forth between two tabs you only need one shortcut, i.e. the one to jump to the most recent tab.
So, this feature is the core of Quicktabs. Ergo, this can be closed!?

**Comment by nanobrad** [comment]
Just to clarify...
You go into: Chrome menu -> More Tools -> Extensions
From the list of all extensions: Top left menu (3 horizontal bars) -> Keyboard shortcuts
![image](https://user-images.githubusercontent.com/597719/83259142-23b0e180-a17d-11ea-94be-31ce1bf72ca5.png)
The only issue I have is that the delay timer is a bit too long for my taste. I like to swap a bit faster, but if you just wait a full second (or so), then it resets, so you can swap back and forth between two tabs.
That is the only difference from Windows' Alt-Tab. In Windows, releasing the Alt button resets the function. In Chrome, releasing the Ctrl key doesn't work, you have to wait for the timeout instead.

**Comment by babyman** [comment]
@nanobrad you can switch back and forth without waiting for the timeout if you use the 'switch to newer tab' shortcut. So Ctrl+Q to go back a tab and then Ctrl+Shift+Q before the timeout to return (I find Cmd+K/Cmd+J work well for this)
