### ISSUE TITLE
feature request: pin tabs

### ISSUE THREAD

**Issue by kin-cho** [babyman/quick-tabs-chrome-extension#290]
Feature request: add support to pin tabs,
to keep them near the top of the tabs list, for quick access.
These tabs should be highlighted.

**Comment by deryb** [comment]
+1!  Also, there should be possibility to assign keyboard shortcuts to quickly switch between "favorite" tabs, ex:

```
Shift + Alt + 1 = Pinned tab #1 - Gmail
Shift + Alt + 2 = Pinned tab #2 - Facebook
Shift + alt + 3 = ...

```

**Comment by deryb** [comment]
Funny I thought at first of another (independant) set of pins, but then what I think I understand you rather mean that Chrome's pinned tabs should have this pin marker in Quick Tabs too right?  Anyway I agree, but still suggest to add shortcuts for these!

And/Or perhaps add a customizable search prefix (ex.  * or !) to only search chrome's pinned tabs.

**Comment by squatto** [comment]
I think a search prefix to search only pinned tabs would be excellent!
