### ISSUE TITLE
Focus is in address bar when selecting a tab from the search popup

### ISSUE THREAD

**Issue by mwalkerr** [babyman/quick-tabs-chrome-extension#291]
When selecting one of the tabs from the search pop-up, the focus goes to the address bar after switching to the tab. Expected behavior would be to switch to the tab without changing the focus. For example, when writing in an input field and switching tabs and then switching back, focus is no longer in the input

**Comment by babyman** [comment]
Thanks for reporting this, I thought I had it fixed (see #277) 

Let me know if it's still an issue after tonights update.

Evan

**Comment by mwalkerr** [comment]
Wow, that's awesome you saw and fixed this the same day that I posted it!! Keep up the good work, I enjoy your extension :)
