### ISSUE TITLE
Add feature to sort the list alphabetically instead of by order of opening

### ISSUE THREAD

**Issue by bthyen** [babyman/quick-tabs-chrome-extension#292]
I'd like to use this for finding duplicate open windows and or group windows together that are related to one another.

**Comment by babyman** [comment]
You could use `/split` to do something like this, e.g. `/split github.com` will give you the option to split all the github tabs from one window into a new window.  There is a `/merge` query command too that does the opposite.

**Comment by babyman** [comment]
What would be considered a duplicate tab?  Exact match on URL, exact match on URL ignoring everything after the #? 

I could then add a command like `/dups [query]` that would filter the list to include duplicate tabs only and maybe add a command to close displayed duplicate tabs?

**Comment by bthyen** [comment]
/dups query would be a great addition
