### ISSUE TITLE
Invoking Quick Tabs on Chrome 79 closes all tabs(?)

### ISSUE THREAD

**Issue by michael-katz** [babyman/quick-tabs-chrome-extension#294]
I've submitted this to Google as feedback on Chrome behavior. But am I the only person experiencing this? Is it my imagination? Thanks:
> Chrome v. 79.0.3945.88 (Mac OS) appears to be incompatible with the ["Quick Tabs" extension](https://chrome.google.com/webstore/detail/quick-tabs/jnjfeinjfmenlddahdjdmgpbokiacbbb). Invoking the extension frequently causes all open tabs to close. I first noticed this bug in Chrome v. 77 or 78, and reported it – but I've just identified "Quick Tabs" as the trigger for tabs closing.
> 
> "Quick Tabs" is not optional for my work. This extension provides an MRU (Most-Recently Used) list of tabs, allowing rapid reopening of closed tabs.
> 
> This is an essential productivity feature that should have been native to Chrome long ago. Instead, the removal of Add-Ons, and current restrictions on Extensions, have both diminished Chrome's native features, and hobbled what Extensions can fill in.
> 
> Please work with the developer to resolve the apparent incompatibility between recent Chrome versions and this essential Extension.

**Comment by babyman** [comment]
One possible cause could be having no key mapping assigned to the 'Close all displayed tabs shortcut', I'm taking that option out inn the next release to replace it with a popup command to make things a little more predictable / deliberate

**Comment by michael-katz** [comment]
@babyman: Thanks, I just (re-)assigned a key mapping to that command, to see if it helps.

I might have slightly misstated the glitch: Chrome doesn't close _all_ tabs, nor exit. It closes all _open_ tabs, while restoring the one tab I requested from the MRU list.

**Comment by michael-katz** [comment]
@babyman: I've experienced no collapsed tabs since I restored a key mapping for the 'Close all displayed tabs' shortcut. If this holds up, I'm assuming you analyzed this accurately. Thanks.

**Comment by babyman** [comment]
Nice, I have completely replaced the 'close all' shortcut with a search command `/close <query>` to help avoid this.

![image](https://user-images.githubusercontent.com/120736/72283552-008df700-360d-11ea-9314-bf8865049278.png)

Please feel free to reopen this ticket if you see the issue again

Evan
