### ISSUE TITLE
Closing multiple tabs from tab list. 

### ISSUE THREAD

**Issue by carl-parrish** [babyman/quick-tabs-chrome-extension#295]
I'm **certain** I used to be able to do do this. Now, whenever I close a tab from the tab list I have to reopen the list. Did I somehow mess up a setting or did the code change? I would like to be able to click on the 'x' for multiple tabs without having to reopen the tab list.

**Comment by babyman** [comment]
That's weird, clicking the 'x' should close that tab and leave the popup open.  That's the behaviour I see locally.  Could you pass on any details about your environment, os, chrome version etc?

Thanks

**Comment by carl-parrish** [comment]
ChromeOS Version 79.0.3945.86 (Official Build) (64-bit)

**Comment by babyman** [comment]
I deployed a small change to limit the propagation of click events in the popup that may fix this.  Please let me know if you're still seeing the issue once your copy updates.

**Comment by carl-parrish** [comment]
Thanks - will let you know as soon as I'm able to test.

**Comment by babyman** [comment]
I'm going to close this, feel free to open it again if you find it's not resolved 😄

**Comment by carl-parrish** [comment]
Not sure if there were recent changes but it worked correctly for me today for the first time in months.
