### ISSUE TITLE
Since 2020.1.5 "Move tab to rightmost position on switch" now applies to normal switching of tabs

### ISSUE THREAD

**Issue by pearj** [babyman/quick-tabs-chrome-extension#296]
Since "2020.1.5" I've noticed that if I have "Move tab to rightmost position on switch" it now applies to any time I switch a tab by hand, or if I am simply switching tabs using the keyboard shortcut ie ctrl+pgup/pgdn and I pause too long.

I think this is related to #174 

Would it be possible to have an additional checkbox that enables the previous behaviour so that "Move tab to rightmost position on switch" only applies if I have actually activated the extension, instead of applying all the time?

**Comment by babyman** [comment]
Dang, I 'fixed' that as part of #174, let me add something to control if the switching happens always or only when switching using the popup.  Any suggestions on the option text would be most welcome :)

**Comment by pearj** [comment]
Maybe for single text, it could be "Only move tab when selected via the extension"

If you wanted to explicitly list both options you could have 2 options like so:

Move tab when:
- The tab is selected by any means, including via the extension
- Only when the tab is selected via the extension

**Comment by byungjikroh** [comment]
I've been experiencing and too hard to find which extension causes this error. 

It happens always even if there is no popup of Quick Tabs. 
I turned off 'Move tab to rightmost position on switch' option.

Looking forward to being fixed it soon!

**Comment by babyman** [comment]
I'm going to push the update now so you should see it in the next few hours, I ended up separating the tab move options:

![image](https://user-images.githubusercontent.com/120736/72039469-40eb1f00-3273-11ea-8506-3feecaf917ee.png)

Defaults should reset the original behaviour.

Evan
