### ISSUE TITLE
Slower than Tab Ahead with many open tabs

### ISSUE THREAD

**Issue by infokiller** [babyman/quick-tabs-chrome-extension#297]
Hi and thanks for this extension, I really like it!
I just tested both this one and [Tab Ahead](https://github.com/janraasch/tab-ahead) with ~450 open tabs. Both of them are using fuzzy search, but Tab Ahead felt more responsive: editing the search query was fast and unaffected by the results computation, while with Quick Tabs the search query editing started to feel slow.
I know it's not a fair comparison, because Quick Tabs actually searches more things, but still wanted to bring this up because it seems possible to improve the responsiveness by doing things more async.

**Comment by babyman** [comment]
Let me take a look, simply debouncing the search results update when editing the search query could make a huge difference.

**Comment by babyman** [comment]
I pushed the debounced version to the store tonight, it feels better to me but will still struggle searching history.

**Comment by infokiller** [comment]
Great, thanks for the quick fix, I'll check it out!

**Comment by babyman** [comment]
I'm going to close this, feel free to open it again if you find it's not resolved 😄
