### ISSUE TITLE
"when no tabs match" stopped working

### ISSUE THREAD

**Issue by ccmdev** [babyman/quick-tabs-chrome-extension#298]
Most recent version about 3 weeks ago broke the "no tabs match" feature.   this is convenient to open a new tab with a search, ONLY if no tab is already open, e.g.:

https://drive.google.com/drive/u/0/search?q=%s

**Comment by babyman** [comment]
I'll take a look, thanks for letting me know.

**Comment by ccmdev** [comment]
![image](https://user-images.githubusercontent.com/59933977/72626362-75a84780-38ff-11ea-9c38-55d083da886a.png)
for clarity...  when users type words that are not found, until recently if they hit <enter> it woudl execute the search string with the %s search term.     Thank you!

**Comment by babyman** [comment]
Perfect thanks, I found the bug this morning and should have a fix deployed by the end of the weekend.  There is also an option to execute the search string even when there are tabs:

![image](https://user-images.githubusercontent.com/120736/72650255-f2621280-394d-11ea-9fdd-76c4b337bbb1.png)

**Comment by babyman** [comment]
I just pushed this fix, let me know if you still see any issues.

**Comment by ccmdev** [comment]
looks great!  thanks for the quick response.   this a excellent tab manager
