### ISSUE TITLE
"/close" or other command doesn't recognize RegEx?

### ISSUE THREAD

**Issue by kissglay** [babyman/quick-tabs-chrome-extension#299]
Seems like statement after commands like "/close" doesn't recognize RegEx even it's what selected in "Search type". Maybe anything after commands is simply taken as literal.
So now one can't close or executes other commands on multiple tabs based on RegEx. (Previously one can do it by pressing "ctrl + shift + d", which is now unavailable).

**Comment by babyman** [comment]
Let me tweak that out, I opted for a substring search because fuzzy searching for command input seemed far too unpredictable.  Regex should be fine since for most users it will be indistinguishable but if they want to get 'fancy' it is at least possible.  Thanks for bring this up!

Evan

**Comment by kissglay** [comment]
Glad to help.

If enabling RegEx in command, will some pretty handy command like:`/mute <))` , to mute any noisy tab, still work? (as long as meta characters are escaped, `/mute <\)\)`)

**Comment by babyman** [comment]
Good point about the mute command, I checked and it won't need escaping because it's special cased before the rest of the search :)

https://github.com/babyman/quick-tabs-chrome-extension/blob/041e428b287a7216795746df97b5bd8f7f8add52/quick-tabs/popup.js#L755-L757
