### ISSUE TITLE
When no tabs match, search using: "%s" not working

### ISSUE THREAD

**Issue by dtreskunov** [babyman/quick-tabs-chrome-extension#302]
First of all, huge thanks for creating and maintaining this extension!

I would like to be able to open a new tab with the Quick Tabs search string as the URL. I tried to use the string "%s" rather than a template including google/duckduckgo/another search engine. What happened then was an error page ERR_FILE_NOT_FOUND

![image](https://user-images.githubusercontent.com/3477960/74062981-5784b300-49a4-11ea-8da5-855970c61941.png)

**Comment by babyman** [comment]
I have deployed an update that should hopefully solve this for you, the empty list code would detect a url search string and open that directly.  Unfortunately the code triggered by ctrl + enter would always try to search with the engine url.

`qz.com` and similar strings should just open in a new tab.

If that's not helpful feel free to reopen this ticket :)

Evan
