### ISSUE TITLE
Get ctrl-e working on Linux, too?

### ISSUE THREAD

**Issue by guettli** [babyman/quick-tabs-chrome-extension#305]
Since I use PyCharm, it would be very nice, if I could use ctrl-e in chrome, too.

I use Linux.

Is there a way to configure chrome or the extension to make ctrl-e work on linux, too?

BTW: This extension is very cool. Thank you very much!

**Comment by babyman** [comment]
Hey @guettli, under extensions, if you click the burger menu on the right you should see the option to configure keyboard shortcuts for extensions (I swear Google doesn't want you to know it's there)!  You can also paste `chrome://extensions/shortcuts` in the browser address bar to open the page directly.

From there you should be able to map the shortcuts, I have cmd+e mapped on my mac:

![image](https://user-images.githubusercontent.com/120736/76377300-e62c7d00-6320-11ea-9b47-9181371095b2.png)

Hope this helps 😄 

Evan

**Comment by guettli** [comment]
@babyman thank you very much for the answer. This works fine. Why not make ctrl-e the default on linux. People using an Jetbrains IDE already have the shortcut in the muscle memory of their fingers.

**Comment by guettli** [comment]
Is there a reason why on linux ctrl-e is not the default. I think ctrl-e as default would make sense. IntelliJ based IDEs are very common today. This means this shortcut is already wide-spread.
