### ISSUE TITLE
delete text if dialog gets opened again

### ISSUE THREAD

**Issue by guettli** [babyman/quick-tabs-chrome-extension#307]
Some minutes ago I searched of "Jir". Now, some minutes later I want to use the coolest chrome extension on planet earth again.

But what's this? Only some lines are visible: 

![Screenshot 2020-03-11 at 11 09 42](https://user-images.githubusercontent.com/414336/76405744-e2ccdc00-6388-11ea-82a1-5aa3c628e2cc.png)

What's going on? I have no clue.

Thank you for following my story.

It would be nice if the text I used in the autocomplete some minutes ago, does get deleted if I open the tool again.

**Comment by babyman** [comment]
@guettli hopefully I can add a happy ending to your story, check the options page for

![image](https://user-images.githubusercontent.com/120736/76415403-85786100-636f-11ea-89cc-d31f577843d4.png)

and uncheck it, if it isn't checked this might be a sad story 😒 

Evan

**Comment by guettli** [comment]
@babyman wow, great. Thank you. One thing is on my mind: What is the best default for this value? Why not make a survey with the users. Which default is the preferred one?
