### ISSUE TITLE
close all tabs

### ISSUE THREAD

**Issue by popoaq** [babyman/quick-tabs-chrome-extension#308]
there used to be a keyboard shortcut to close all tabs that matches the query, now it seems I can only close one tab at a time. 

Is this an intentionally regression? if not how do I close all matching tabs with one shortcut?

**Comment by babyman** [comment]
The shortcut had caused some issues for people in the past so I reworked the way batch commands work in Quick Tabs.  You can still batch close tabs with `/close <optional regex query>`

There is a list of commands here (https://github.com/babyman/quick-tabs-chrome-extension#commands) including window tab splitting and merging etc.

I hope you find this useful 😄 

Evan

![image](https://user-images.githubusercontent.com/120736/77003475-d2da6c80-6933-11ea-8ae8-7866db555f89.png)

**Comment by popoaq** [comment]
oh, nice. thank you so much @babyman !
