### ISSUE TITLE
No tabs showing up!

### ISSUE THREAD

**Issue by Nidkid** [babyman/quick-tabs-chrome-extension#310]
![quick-tabs-malfunction](https://user-images.githubusercontent.com/5214401/78271205-dfd19100-74d9-11ea-9209-2a9eea2ac530.png)

**Comment by Nidkid** [comment]
It was working fine until today. As you can see I have 5 tabs open and none of them are being shown in the extension.

**Comment by babyman** [comment]
@Nidkid, that's very strange, it has the tabs recorded (the 5 count on the QT icon) but it's not showing them in the popup window, I'm not sure if you are still seeing this issue but if you are can you inspect the popup and see if it has any errors logged?

You can open the popup window in a tab using `chrome-extension://jnjfeinjfmenlddahdjdmgpbokiacbbb/popup.html` from there right click in the tab and inspect it.  From there you should be able to see the console output;

![image](https://user-images.githubusercontent.com/120736/78323032-95cec680-753e-11ea-9c2b-8b6dfdc0e11d.png)

Thank you for taking the time to report this issue =D

**Comment by Nidkid** [comment]
I'm not currently getting that issue anymore. If it happens again I'll
remember to check what you're asking for and update this post.

**Comment by ErikFontanel** [comment]
I'm having the same problem, and this is what shows up in the console:

Log:
```console
Uncaught TypeError: Cannot read property 'title' of undefined
    at Object.extract (popup.js:880)
    at fuzzy.js:118
    at Array.reduce (<anonymous>)
    at Object.fuzzy.filter (fuzzy.js:115)
    at FuzzySearch.searchTabArray (popup.js:887)
    at FuzzySearch.AbstractSearch.executeSearch (popup.js:786)
    at performQuery (popup.js:726)
    at HTMLDocument.<anonymous> (popup.js:391)
    at j (jquery-3.2.1.min.js:2)
    at k (jquery-3.2.1.min.js:2)
```
![image](https://user-images.githubusercontent.com/917819/78548398-09075f80-7801-11ea-9941-33d5649899f0.png)

Full log:
[quicktabs.log](https://github.com/babyman/quick-tabs-chrome-extension/files/4437673/quicktabs.log)

**Comment by fede1024** [comment]
I've been having the same issue for several months and I get the same error (with a slightly different stacktrace since I use a different search algorithm):

```
Uncaught TypeError: Cannot read property 'title' of undefined
    at StringContainsSearch.<anonymous> (popup.js:1051)
    at Array.map (<anonymous>)
    at StringContainsSearch.searchTabArray (popup.js:1050)
    at StringContainsSearch.AbstractSearch.executeSearch (popup.js:786)
    at performQuery (popup.js:726)
    at HTMLDocument.<anonymous> (popup.js:391)
    at j (jquery-3.2.1.min.js:2)
    at k (jquery-3.2.1.min.js:2)
```

For some reason on of the tabs in `bg.tabs` is `undefined`.

**Comment by Deco** [comment]
Ditto

**Comment by NicoWeio** [comment]
Related issue: #275

**Comment by babyman** [comment]
Issue #313 describes something that seems similar
