### ISSUE TITLE
Quick Tabs fails to update and breaks after tabs are closed via OneTab

### ISSUE THREAD

**Issue by ColeWunderlich** [babyman/quick-tabs-chrome-extension#313]
When using the OneTab extension to collapse/close tabs, quick tabs fails to realize the tabs are closed and update accordingly.  Closing multiple tabs with one tab also seems to "corrupt" quick tabs, causing no tabs to be displayed and the tab switching feature to no longer function.

I have not been able to figure out a way to get quick tabs to refresh/update so it is aware of currently open tabs (and aware that many of the previous tabs were closed).

**Comment by babyman** [comment]
I'll take a look and see if I can recreate the issue with OneTab, it may help troubleshoot a similar issue reported in #310

**Comment by ColeWunderlich** [comment]
Thanks!

Quick update:  I have been having a hard time reproducing the problem.

Further details:  It involved closing ~55 tabs simultaneously, and working with multiple chrome instances/windows open at once.

Easy workaround: I finally figured out how to easily reset the extension.  I left click on the extension icon --> manage extensions --> quickly toggle the extension off and on again in the page that pops up.  After doing this it reloads instantly and functions correctly.

**Comment by tobiasl-sportsbet** [comment]
> Thanks!
> 
> Quick update: I have been having a hard time reproducing the problem.
> 
> Further details: It involved closing ~55 tabs simultaneously, and working with multiple chrome instances/windows open at once.
> 
> Easy workaround: I finally figured out how to easily reset the extension. I left click on the extension icon --> manage extensions --> quickly toggle the extension off and on again in the page that pops up. After doing this it reloads instantly and functions correctly.

Just to confirm this, I have the same issue every now and then with OneTab but it hasn't been dependent on the number of tabs I am closing, at least as far as I can tell.

I've also resorted to what @ColeWunderlich suggested, quickly disabling and enabling the extension completely resets it. Interestingly, incompletely closing and opening Chrome doesn't help.
