### ISSUE TITLE
"Recently Closed" list order not updating on Chrome/Catalina

### ISSUE THREAD

**Issue by mQkatz** [babyman/quick-tabs-chrome-extension#316]
On Chrome v. 83.0.4103.61, on Mac OS Catalina (10.15.3), I'm consistently seeing that my most-recently-closed tabs do not appear at the top of the list. Instead, the top gets clogged with certain tabs that I closed earlier – sometimes hours earlier, and sometimes as duplicate entries.

In case this helps: The tab names that clog the top of the list seem to be (mostly or always) Google Docs that are shared within my company's hosted Google Suite. Disabling/enabling (or removing/restoring) the Quick Tabs extension clears the stale entries – but that obviously discards the whole tabs history, so it's not a solution.

For comparison, Quick Tabs is working perfectly for me on all recent Firefox versions (e.g., 76.0.1 ). But I'm not opening work-related Google Docs in Firefox.

Thanks for any insight into why this is happening! I love the extension, and it's a surprise not to be able to rely on its sort order.

**Comment by mQkatz** [comment]
@babyman I love this extension, but this weird bug has made it borderline unusable for me on Chrome. (It still works flawlessly on Firefox.) Any suggestions for debugging the cause, or trying a workaround? Many thanks.

**Comment by babyman** [comment]
Strange, thanks for following up on this.  The closed tabs list shouldn't get reordered, tabs are added to the beginning of the list and then resized back to its max size.

I just want to check, this is happening when the search box is empty:

![image](https://user-images.githubusercontent.com/120736/90775841-56273200-e2c7-11ea-80ad-5c6c7956169d.png)

since the tabs will be reordered (within their section) once you start typing.

**Comment by mQkatz** [comment]
Hi Evan: Thanks for looking at this. (You quickly helped me debug my only previous Quick Tabs glitch – where removing all keyboard shortcuts had broken the extension's behavior.)

The **Recently Closed** list (which is all that interests me) _does_ change when I start typing into the search box. But not in any especially meaningful way. The items that populate right under **Recently Closed** aren't particularly recent. Also, they aren't particularly relevant – i.e., they're matching on substrings somewhere within the content, whereas I'm trying to match what I remember: a page title.

![image](https://user-images.githubusercontent.com/12901606/90828583-20983e00-e2f3-11ea-991b-db210d021a5e.png)

By contrast, on Firefox, the **Recently Closed** list automatically keeps itself up to date, promoting the most-recently-closed tab titles to the top as expected. Also, I've just confirmed that Quick Tabs' **Recently Closed** list is working as expected on:

* Chrome on Mojave.
* Chrome on High Sierra.
* Chrome on the same Catalina machine where I'm experiencing this glitch – except, in a separate Chrome session where I'm logged in with a "personal" profile.

Common to all these ^ three environments: Limited history of pages viewed. And limited or no viewing of corporate GSuite or Atlassian pages.

So in case this helps: It seemingly isolates the glitch to the Chrome/Catalina session where I'm logged in with my workplace Google SSO persona, and where I've loaded lots of Google Docs/Sheets, Jira, and Confluenza pages. I _seem_ to recall that what first spammed the top of the **Recently Closed** list were GDocs on the same Google SSO account – sometimes multiple copies of the same GDoc, closed hours before other tabs not displayed.

Thanks again, and please let me know if I can do anything else to help you reproduce this – and/or, if you have any ideas for working around it. I've tried disabling/re-enabling and removing/reinstalling the extension, but it keeps coming back with the same glitch.

**Comment by babyman** [comment]
Quick question, are the search settings the same between each of the browser instances?

![image](https://user-images.githubusercontent.com/120736/91457920-eda1fd00-e852-11ea-9bc8-8fed4add1489.png)

These settings can make a huge difference to the search results.

**Comment by mQkatz** [comment]
Yes, identical:
<img width="571" alt="image" src="https://user-images.githubusercontent.com/12901606/91482638-38277780-e85b-11ea-9996-f7aa48d4f9f7.png">

**Comment by mQkatz** [comment]
But wait: Haven't I already told you you're brilliant, the last time you debugged this great extension for me?

I misread your email at first, and conformed all the non-matching settings on my broken session to match my working session. And I _think_ this unblocked the **Recently Closed** list to work properly again! If that holds up, one of these changes was the fix:

![image](https://user-images.githubusercontent.com/12901606/91533268-760cb600-e8c4-11ea-9161-6972f8123ec3.png)

**Comment by babyman** [comment]
I'm glad you got that sorted out, do you think it was the keyboard code that was the cause of the issue? or some combination of the settings above?

I wonder if there is a more robust way to handle the keyboard shortcuts, it's been ages since I looked at how best to handle them.

**Comment by mQkatz** [comment]
False non-alarm: The **Recently Closed** list got clogged again. 🤦  Still debugging. I've disabled/enabled the extension, and set/reset some of the options. I'll let you know if/when I locate the actual trigger.
