### ISSUE TITLE
Add option to search tab groups in chrome

### ISSUE THREAD

**Issue by saldad1772** [babyman/quick-tabs-chrome-extension#319]

**Comment by babyman** [comment]
Looks like there is no API for tab groups at all for the moment ( https://bugs.chromium.org/p/chromium/issues/detail?id=930988 ) but once there is I will make adding support a priority

**Comment by Poopooracoocoo** [comment]
now see https://bugs.chromium.org/p/chromium/issues/detail?id=1106846
