### ISSUE TITLE
Chrome rights necessary, if so, why

### ISSUE THREAD

**Issue by makedir** [babyman/quick-tabs-chrome-extension#321]
I noticed this addon wants the following rights:

- read and CHANGE your browsing history
- read and CHANGE your bookmarks

Why? For what? Why does it want read and WRITE access to history and bookmarks? Doesnt sound very trustworthy.

**Comment by babyman** [comment]
Unfortunately Chrome makes no distinction between **real only** and **read/write** permissions in its manifest.  Quick Tabs never modifies your bookmarks or browser history ( https://github.com/babyman/quick-tabs-chrome-extension#permissions ) but does need those permissions to search your open tabs, bookmarks and browser history.

The API docs for extension permissions can be seen here https://developer.chrome.com/extensions/declare_permissions#manifest

It's a shame as I have been very deliberate to limit the permissions required by Quick Tabs to the very minimum, but in the end I fully respect your concerns (I have them myself when installing extensions).  It's ridiculous for me to suggest you review the code but the way Chrome permissions work that's really the only way to check **any** extension for bad behaviour.

In the end you have to be comfortable with the extensions you install, Quick Tabs is very safe, it's an open source personal project, but you must decide for yourself if any extension is worth the risk to your privacy and data.

Hope that's helpful,

Evan

**Comment by makedir** [comment]
I dont want it to search my bookmarks and history, just tabs. Thats what the name of the addon suggests, no? Tabs search.

**Comment by babyman** [comment]
Even if the extension didn't support bookmark search (which IMHO is very helpful) it would still be asking for "read and CHANGE your browsing history" permission.

Most of the time you will only see open tabs in your searches, it will search bookmarks if your tab search results are limited but that can be disabled on the options page.  Full history searches are only triggered on request using `/h <query>` or a query that starts or ends with 3 spaces.

As I said, you really do have to be comfortable with the extensions you install and the permissions they are requesting, but, i would definitely suggest taking Quick Tabs for a spin, if you don't like it or it's not meeting your needs it's easy to uninstall.
