### ISSUE TITLE
Restrict Tab List to Pinned Tabs

### ISSUE THREAD

**Issue by holygamer** [babyman/quick-tabs-chrome-extension#324]
I have several YouTube tabs pinned. But when there's lots of tabs open I can't see the tab names as the tab width is too short so I can't tell which tab which belongs to which YouTube channel. That's why I use your extension. 

However when I search for "YouTube" in your extension, it shows results for all tabs not just pinned tabs. Could you add an option to only show results for pinned tabs or perhaps you can add an option so that when a certain search is done then you'll only see results for pinned tabs.

**Comment by NicoWeio** [comment]
https://github.com/babyman/quick-tabs-chrome-extension/compare/master...NicoWeio:filter-pinned

I went ahead and implemented a special query `:pin` which will show all pinned tabs. 

However, I don't expect this to be merged the way it is. We'd need to standardize special queries. We already have `<))` for audible tabs, but I don't find that intuitive, and we won't be able to "asciisize" every special query. Also, it would be more useful to have special queries act as filters, in addition to a query, just the way prepended/appended spaces work.

**Comment by NicoWeio** [comment]
Related: #293

**Comment by babyman** [comment]
You can search pinned tabs only using `/p <query>`, if you set the option to "Keep last searched string in search box" that would essentially restrict the list to only pinned tabs (at least as long as you don't change the search string.

Hope this helps.

**Comment by NicoWeio** [comment]
Wow, how could I implement this myself without noticing it's already in there. 😂
Thanks @babyman!
