### ISSUE TITLE
Extension consuming large amounts of RAM and CPU

### ISSUE THREAD

**Issue by babyman** [babyman/quick-tabs-chrome-extension#331]
Issue reported by email by **Frank Funny**:

I love your extension. It is very useful for me but from yesterday, I'm having Chrome stuck and I have identified that your extensions keep "eating" RAM (until 6GB) and CPU (I have been able to identify this obtaining the PID of the process in Chrome's Task Manager and reviewing the data in the Windows 10 Task Manager).

Please, if you can look at these problems and provide a solution, it would be great because your extension is really good in functionality.

**Comment by ck--** [comment]
I also noticed the same problem. A lot of RAM and CPU is consumed by the extension especially when there are many tabs open. I have now removed the extension.

**Comment by jaekyeom** [comment]
Strange. For me, it was okay until the last restart of my system (and of course, Chrome). Plus, the one installed locally via the developer mode doesn't seem to have this issue.
