### ISSUE TITLE
Chrome Tabs STACKED VERTICALLY?

### ISSUE THREAD

**Issue by mywebguytaylor** [babyman/quick-tabs-chrome-extension#332]
I am looking for a chrome extension which allows me to automatically sort and group Chrome tabs...VERTICALLY. (not horizontally). I have just spent 10 hours trialing every tab organizer extension I could find, and none of them have this feature. for example, if I have 10 tabs open "domain1.com" it will nicely organize them into a vertical bucket, drop down etc, is that possible yet with Chrome?  If you find something like this, can you message me on skype?  SMARTCHOICEWEB

**Comment by Pictor13** [comment]
Try [Tabs Outliner](https://chrome.google.com/webstore/detail/tabs-outliner/eggkanocgddhmamlbiijnphhppkpkmkl).
Not perfect but useful.

Chrome doesn't allow a real rearrangement of the UI for the tabs, so no extension will give you what you want.
Switch to Firefox and use TreeStyleTabs.
