### ISSUE TITLE
Virtual desktop support

### ISSUE THREAD

**Issue by Poopooracoocoo** [babyman/quick-tabs-chrome-extension#337]
also referred to as 'spaces' on macOS, 'virtual desks' on Chrome OS, or 'workspaces' on GNOME. 

i'm not sure if QT supports them or not already, but just requesting it anyway

thank you for your continued development and extension :)

**Comment by babyman** [comment]
It should work just fine, the popup list loads on the current active window and lists all tabs across all browser windows and will jump you to the selected window (and space).  At least on OSX.

Hopefully that's the behaviour you would expect, would love to hear your thoughts :)

Thanks,

Evan

**Comment by Poopooracoocoo** [comment]
Well sometimes I want to view and search for tabs on the current virtual desktop. 

Sorry, I should've explained more! I'm usually better at reporting issues and making feature requests than this :P

**Comment by babyman** [comment]
Ahh got it, I don't think there's a way to determine anything about the windows/tabs in a space, the docs mention `setVisibleOnAllWorkspaces` (https://developer.chrome.com/docs/extensions/reference/app_window/#type-AppWindow) but that's all i can see :|

If you want to search tabs in the current window you can start your search string with `/w [query]` but I know that's not the same :(

https://github.com/babyman/quick-tabs-chrome-extension#commands

Evan
