### ISSUE TITLE
BUG: Pressing delete symbol closes tabs list with Brave

### ISSUE THREAD

**Issue by u2d4** [babyman/quick-tabs-chrome-extension#339]
Pressing the cross (x) at a list entry closes tab tab (as expected) but also removes the popup list from screen (not expected). With Google Chrome the popup list stays (as expected).

**Comment by babyman** [comment]
I'm not experiencing this in the current version of Brave although I don't often use that icon;

![image](https://user-images.githubusercontent.com/120736/106367841-962d1f00-6313-11eb-8248-7098375da0a3.png)

**Comment by VimalMollyn** [comment]
Same here, I don't seem to be facing this issue either. 
![image](https://user-images.githubusercontent.com/62076354/106933186-a5aace80-673e-11eb-858a-82d02d23074c.png)
