### ISSUE TITLE
Tabs on Other Devices 

### ISSUE THREAD

**Issue by MaximumDerek** [babyman/quick-tabs-chrome-extension#342]
I was wondering if you had on your roadmap since you have the ability to search through history if you were going to add the ability to search through open tabs on other devices?

**Comment by babyman** [comment]
Hey @MaximumDerek,

Thanks for touching base, I've never actually considered that but it would be really neat, right now the extension is not really setup for sharing any information between browser installs but something to consider.  It's tough for me to find much time to do more than maintain the code at the moment though :|

Evan

**Comment by MaximumDerek** [comment]
No worries, it came up because I use my work computer as my main computer,
but have an iPad. I haven't found any other extensions that might show the
tabs on other device's info as a quick dropdown, so it's a fairly unsolved
issue.

Thanks for reaching out!
Derek
