### ISSUE TITLE
Why doesn't it say anywhere how to trigger this?

### ISSUE THREAD

**Issue by alper** [babyman/quick-tabs-chrome-extension#348]
I'm looking through the documentation and can't find it. Command-P it isn't. Where is it detailed?

**Comment by babyman** [comment]
I assume you mean show the extension :), It's in the docs:

Shortcut key to launch popup window from most tabs (default ctrl+e, cmd+e on Mac, ctrl+q on Linux).

you can change the keys using the extensions shortcuts settings ( chrome://extensions/shortcuts )
