### ISSUE TITLE
Sometimes doesn't switch to window with tab

### ISSUE THREAD

**Issue by tarasdi** [babyman/quick-tabs-chrome-extension#35]
Hi,

I'm finding I can recreate this problem on at least two installations of Chrome. I find that if I hit ctrl-m, type in the tab I'm looking for, find the tab, and hit enter, sometimes the focus doesn't change to this tab. I've found that this happens very consistently if the tab is the tab with focus _in a different window_.

**Comment by babyman** [comment]
Closing this since this bug is over 2 years old and the code has changed significantly in that time.
