### ISSUE TITLE
The "/subs" command performs regex search

### ISSUE THREAD

**Issue by kissglay** [babyman/quick-tabs-chrome-extension#362]
As the title suggests. Without the command, if "subs search" is selected in the option, it indeed performs subs search". But with the `/subs` command issued, the following phrases seem to be treated as regex.
Didn't try `/fussy` and `/fuse`, but `/regex` works as expected

**Comment by Max33Verstappen** [comment]
stale

**Comment by Max33Verstappen** [comment]
stale

**Comment by Max33Verstappen** [comment]
stale

**Comment by Max33Verstappen** [comment]
a

**Comment by Max33Verstappen** [comment]
stale
