### ISSUE TITLE
Chrome Web Store says: This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.

### ISSUE THREAD

**Issue by pmorch** [babyman/quick-tabs-chrome-extension#380]
![image](https://github.com/user-attachments/assets/23593a37-7579-43ef-9e12-dde29ffeb8d4)

I'm guessing this is because it uses a v2 manifest. If that is the case, this is covered by #375 "Update to manifest v3?"

**Comment by babyman** [comment]
Updated code has been published, the extension has been migrated to v3...

<img width="346" alt="image" src="https://github.com/user-attachments/assets/75c76e2f-b8e9-4c51-a970-d153aeac3ac4">
