### ISSUE TITLE
Change the default shortcut to Ctrl+Q

### ISSUE THREAD

**Issue by hababr** [babyman/quick-tabs-chrome-extension#382]
The current default shortcut Ctrl+E does not work on Windows (and I believe on Linux) right after install, you have to reassign it. That's because it is used as [Chrome shortcut](https://support.google.com/chrome/answer/157179#zippy=%2Caddress-bar-shortcuts) for "Search from anywhere on the page".

Also I think the "Q" is better associated with the name of the extension :)

**Comment by babyman** [comment]
Interesting, I wondered why you had changed that :).  I only have a Mac and Cmd+Q quits Chrome, I picked Cmd+E because it's the same shortcut as IntelliJ.  

Maybe best to default to Ctrl+Q for PC and Linux and keep Cmd+E for Mac?

**Comment by hababr** [comment]
Yes, I think you are right.
