### ISSUE TITLE
Provide option to keep the order of the open tabs

### ISSUE THREAD

**Issue by mybecks** [babyman/quick-tabs-chrome-extension#41]
Hello,

It would be nice if a feature can be added, which keeps the order of my open tabs in your quick-tabs-extension. 
Example:
Browser looks like this:
tab1, tab2, tab4, tab3, tab7, tab10, ...
Quick Tabs should order his list the same structure as the browser. Currently you add the latest tabs to the top, ignoring where they are opened. This feature as an option would be wonderful ;)

BR,
mybecks

**Comment by keymon** [comment]
+1

**Comment by Dyphen** [comment]
+1

**Comment by stalingraddd** [comment]
Please make an option to sort shown tabs in "quick tabs" in that order, how they are ordered in browser window. It's very hard to find tabs because i remember one order, and in "quick tabs" i see another

**Comment by goldencut** [comment]
+1!! Desperately! :P
