### ISSUE TITLE
Setting the width of the tab-list

### ISSUE THREAD

**Issue by ParoTheParrot** [babyman/quick-tabs-chrome-extension#54]

**Comment by babyman** [comment]
@ParoTheParrot this can actually be achieved using the custom css option, just paste something like this into the custom css box on the Quick Tabs options page:

  body {
    width:500px;
  }

A lot of customization can be achieved using the css options... https://userstyles.org/styles/99938/better-styling-for-chrome-extension-quick-tabs

Evan
