### ISSUE TITLE
grayed out item in list that opens a new instance instead of existing tab

### ISSUE THREAD

**Issue by davecazz** [babyman/quick-tabs-chrome-extension#57]
It seems like this only happens with one web site so far, chat simply https://chatsimply.com/

but you have to be logged in and viewing a chatroom. this site appears grayed out in the list. I can select it but it will not select the existing tab, it will instead open a new instance of this web site.

**Comment by babyman** [comment]
@davecazz I just wanted to check in and see if you are still experiencing this issue with the latest code (released a couple of days ago)?

Thanks

**Comment by babyman** [comment]
I can't seem to reproduce this so I will close it for the moment...
