### ISSUE TITLE
Targeted search (open, closed, bookmarks, history)

### ISSUE THREAD

**Issue by JindrichPilar** [babyman/quick-tabs-chrome-extension#61]
IntelliJ IDEA allows you to search for different types of content. It would be great to be able to specify where to search. Via different shortcuts or with some prefix like "b:" search bookmarks.

search all (sorted first tabs, then bookmarks, then history)
open tabs
closed tabs
bookmarks search
history search

**Comment by oarrabi** [comment]
@babyman I am working on implementing this, for the first PR I am thinking of adding the bookmarks after all the tabs (open/closed)

**Comment by babyman** [comment]
@oarrabi I see your pull request and will hopefully have time to merge it tonight, thanks for this =)

**Comment by oarrabi** [comment]
@babyman I am in love with this tool, I use command-t and intellij open everywhere feature, so this plugin is just what I want.
Do you have a milestone or future features that you are planning to implement, I would be happy to help :)
