### ISSUE TITLE
Option to change font

### ISSUE THREAD

**Issue by nab128** [babyman/quick-tabs-chrome-extension#64]
Would be nice to have the tab list shown with the same font as used in the tabs themselves. On Windows at least the tab list defaults to something like Verdana? and looks a little discordant to my eyes.

Other little visual improvements would be to reduce line spacing when not showing urls, and turn off the line separators.

**Comment by babyman** [comment]
@nab128 it's possible to inject your own custom css into the extension using the options page, @bunnyslippers has created a great example of what can be achieved here... https://userstyles.org/styles/99938/better-styling-for-chrome-extension-quick-tabs

I would love to see what you create and would happily promote it here...

Evan
