### ISSUE TITLE
I've developed some very nice CSS for this extension.

### ISSUE THREAD

**Issue by fcherman** [babyman/quick-tabs-chrome-extension#66]
I keep reapplying it after you push an update, but it would be nice if it were integrated. I've also posted it on userstyles.org, where 33 people have installed it so far. It allows you to see more tabs at a glance to minimize scrolling. https://userstyles.org/styles/99938/better-styling-for-chrome-extension-quick-tabs

Feel free to help yourself to all or just part of it. Love your extension!

**Comment by babyman** [comment]
@fcherman I just wanted you to know that the UI style update I just pushed out should be stable for the foreseeable future, I know it will impact you but the popup was looking quite stale.  If you need any extra classes etc to make your css work please let me know.

Evan

**Comment by fcherman** [comment]
​Evan, you are so sweet to let me know! I will take a look and update my
CSS. Thanks again.

Frances​

**Comment by fcherman** [comment]
May I make a few suggestions for your latest "readme" file?


   -
   - bookmarks included only a few open tabs match

This sentence is missing one or more words, and its meaning is unclear as a
result. If you would kindly explain to me what you are trying to say, I
will  give you a better way to say it. I'm a marketing writer by trade, and
a native English speaker.


   -
   - if your search starts with 1 space ' ' include bookmarks
   - if your search starts with 2 spaces ' ' only search bookmarks

You have a great opportunity here to help remind people of this feature and
how to use it, which they might otherwise forget. Replace the "Search"
placeholder text in the search field with this:

*Space before: incl. bookmarks. Two spaces: only bookmarks*

The number of characters just fits in the search field
​, but if you find that it doesn't, you can abbreviate bookmarks as
"bkmrks."​

Lastly, I don't know if it's just my setup, but when I turn off my custom
CSS and turn off Stylish completely to make sure I don't have any old QT
code that might be affecting it, the box on the right drops off the edge of
the popup and there's too much space on the left. Here's a screenshot.
[image: Inline image 1]

​Best wishes,

Frances​

**Comment by babyman** [comment]
&lt;blush/&gt; I am also a native English speaker, I have updated the readme to actually make sense (I hope), please let me know what you think :)

* search your bookmarks:
  * bookmarks are automatically searched when only a few tabs match your search string
  * if your search string starts or ends with 1 space ' ' bookmarks are always included
  * if your search string starts or ends with 2 spaces '  ' only bookmarks are searched

I tweaked the search to make it easier to add bookmarks by including spaces at the end of the query as well and I am changing the search placeholder to "Search, start or end with spaces for bookmarks".

I'm not quite sure why the popup window would not render correctly for you and unfortunately your attachment seems to be missing, any chance you can reattach it?

Thanks so much for taking the time to read the readme (I wonder sometimes...) and your suggestions.

Evan

**Comment by fcherman** [comment]
Evan, I didn't realize this conversation was appearing on your GitHub page!
I would have been more careful about making assumptions! Thanks for being a
good sport.

Regarding the bookmarks text, the first point is much clearer now. :-) For
the second and third points, I find the quotation marks and space more
confusing than helpful. I think everyone knows what a space is, so there's
no need to demonstrate, and having quotation marks with nothing visible
between them is just confusing. I also think it's clearer when instructions
are given as directives, hence, this is what I would recommend for the
second and third bullets:


   - Add a space at the end of your search string to search bookmarks along
   with tabs
   - Add two spaces at the end of your search string to search only
   bookmarks


I am again embedding the screenshot showing the shift to the right. I will
also attach it (rather than just embedding it) in case that's the problem.

Best wishes,

Frances

[image: Inline image 1]

**Comment by fcherman** [comment]
Okay, the CSS has been updated! Dealing with the separators was a bit
tricky since in my layout they don't actually divide anything, but I found
what I think is a reasonable solution. I suppose I could have simply hid
them with "display:none" and just distinguished the groups by color. Or I
could have made them full-width so they actually did separate the groups,
but that would sacrifice some of the "real estate" available for tabs if
the number of tabs above the separator was not an exact multiple of 3. Oh
well, there are many ways to do it.

You'll see the new CSS here:
https://userstyles.org/styles/99938/better-styling-for-chrome-extension-quick-tabs

Frances

**Comment by fcherman** [comment]
Okay, I just talked myself into it. I made the separators full-width. :-}

**Comment by babyman** [comment]
Looks awesome, I hope you don't mind but I grabbed your screenshot from userstyles and added it to the readme and google store pages =).

Your bug screen cap is still not coming through, I wonder if you have to attach it directly through the github webpage?

Evan

**Comment by fcherman** [comment]
I don't mind at all. I'm flattered. I'll see if I can find a way to send
you the screenshot on GitHub.

**Comment by fcherman** [comment]
Evan, I tried completely removing my custom CSS (rather than commenting it out) in order to make sure that wasn't causing the shift problem, and apparently it was. With the custom CSS removed, the default styles worked fine. No need to send you a screenshot. (But I LOVE my custom styles, so I'm putting them back in).

Frances

**Comment by fcherman** [comment]
Evan, FYI, if you're on a Mac and want to take a screenshot of just the popup without getting any other part of your screen, press command-shift-4, then hit the spacebar. The cursor will turn into a camera icon. Hover the camera over the window you want to shoot and hit the spacebar again. It will get a nice clean shot of the window with an attractive drop shadow, and nothing else on your screen will be visible.

**Comment by babyman** [comment]
Awesome, I'm relieved that the defaults are rendering properly for you =)

Thanks for the screenshot tip, I always use cmd+option+shift+4 and forget about the rest! I think I will redo the screen caps and add some text to describe the extensions functionality more, things like the shortcuts keys.

Evan
