### ISSUE TITLE
Loss of focus when tabbing

### ISSUE THREAD

**Issue by ajgrayson** [babyman/quick-tabs-chrome-extension#67]
When I switch tabs using this extension the window some how loses focus, but not entirely. Windows still thinks its the active window but I can't interact with it. I have to ALT+Tab out then ALT+Tab back into to be able to interact with it (e.g. use the keyboard).

Chrome version 39.0.2171.71 m

**Comment by cve** [comment]
+1

**Comment by babyman** [comment]
@cve which OS are you running?

**Comment by cve** [comment]
Debian 8

wt., 13 paź 2015, 05:03 Evan Jehu użytkownik <notifications@github.com>
napisał:

**Comment by babyman** [comment]
Clearing out some of these really old, abandoned issues.
