### ISSUE TITLE
Quick Tabs Not Showing Open Tabs Today (Was Working About 1-2 Weeks Ago)

### ISSUE THREAD

**Issue by aakash-shah** [babyman/quick-tabs-chrome-extension#70]
Hello!  Quick Tabs was working about 1-2 weeks ago, and when I came back from the break, Quick Tabs is not longer showing me any results with or without a search query.

No changes were made to my computer afaik.  I tried the following with no luck:
1. Restarted Chrome
2. Restarted my computer 
3. Disabled and re-enabled the addon
4. Uninstalled and re-installed the addon.

I am using Chrome 39.0.2171.95 m on Windows 8.1 Enterprise 64bit.

I attempted to open background.html by going into Manage extensions and then clicking on background.html in the Developer mode area as suggested at https://github.com/babyman/quick-tabs-chrome-extension/issues/27, but I do not see any Red x/errors.  I right clicked the Quick Tabs icon from the toolbar and clicked on Inspect Popup, and I get an error that states "Uncaught ReferenceError: doT is not defined (anonymous function)" at "sandbox.html:76":

![image](https://cloud.githubusercontent.com/assets/9782485/5598712/cb52e762-926f-11e4-85a8-3d3ec7322df6.png)

The tabs I have open are not in Ingonito mode either.

Please let me know if I can provide any other information, or if there are any other troubleshooting steps I can take.

Thanks!

**Comment by babyman** [comment]
That's a strange issue, it seems that the browser is trying to execute the javascript block before it has loaded the doT script file.  I will tweak out the sandbox page and see if that helps...

**Comment by aakash-shah** [comment]
Thank you for your help.  I checked my extensions this evening and the version stated "2015.1.2", but no results are still appearing.  I uninstalled and reinstalled it with no success, and a restart of the browser did not help either.

The error is similar to before, except that the doT error is now on line 77:
![image](https://cloud.githubusercontent.com/assets/9782485/5601783/a3435cee-92cd-11e4-82f0-f7cf7c5b30bd.png)

Not sure if this matters, I should also note that the icon in the toolbar does appear to correctly reflect the number of open tabs, and the count changes as I open and close tabs:
![image](https://cloud.githubusercontent.com/assets/9782485/5601785/eb979c9e-92cd-11e4-87b7-8cc96ebb046c.png)

Please let me know if I can provide any other information.  

Thanks!

**Comment by babyman** [comment]
I wonder if this version of sandbox.html ( https://gist.github.com/babyman/845806d07fda6d3de8e8 ) will resolve the issue?  I have embedded all of the javascript in the html file, even if this fails to work it might give a more informative error message.

Can you replace the version in your local Quick Tabs directory and give it a try?  I believe the directory is here C:\Documents and Settings\*UserName*\Local Settings\Application Data\Google\Chrome\User Data\Default\Extensions\jnjfeinjfmenlddahdjdmgpbokiacbbb 

Thanks

**Comment by aakash-shah** [comment]
Hello!  My sandbox.html file was located under the AppData folder, and not the LocalAppData (in case that matters) at "C:\Users\%username%\AppData\Roaming\Google\Chrome\User Data\Default\Extensions\jnjfeinjfmenlddahdjdmgpbokiacbbb\2015.1.2_0".

I closed Chrome, replaced sandbox.html and then restarted Chrome.  After the browser had loaded, I saw that the QuickTabs icon showed the number of open tabs.  However, when I attempted to click on it, consistently crashed Chrome.  I use Microsoft EMET (Enhanced Mitigation Experience Toolkit) and so I disabled all protections for Chrome just in case (besides Windows Defender, this is the only other protection I use on this computer).  I experienced this crash consistently on 3 separate attempts to click on the QuickTabs icon.

After replacing the original sandbox.html file, it is no longer crashing, but it is still not showing me any results.

I am not sure where the Chrome crash files are stored (the CrashReports folder is empty).  The Windows Event Log, showed this (in case it helps):

Log Name:      Application
Source:        Application Error
Date:          1/6/2015 9:30:25 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      <snip>
Description:
Faulting application name: chrome.exe, version: 39.0.2171.95, time stamp: 0x548243f3
Faulting module name: chrome.dll, version: 39.0.2171.95, time stamp: 0x54823ff4
Exception code: 0xc0000005
Fault offset: 0x0010130c
Faulting process id: 0x41b0
Faulting application start time: 0x01d029d60bb27139
Faulting application path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Faulting module path: C:\Program Files (x86)\Google\Chrome\Application\39.0.2171.95\chrome.dll
Report Id: b24ea13a-95c9-11e4-82a6-f8b1569fc9b9
Faulting package full name: 
Faulting package-relative application ID: 

Please let me know if I can provide any other information or run any other tests.

I appreciate your time and help with this.

Thanks!

**Comment by aakash-shah** [comment]
I remembered that I had relocated my Chrome profile and that is why it was under AppData.  On another computer where I am experiencing the same problem, it is located at C:\Users\%username%\AppData\Local\Google\Chrome\User Data\Default\Extensions\jnjfeinjfmenlddahdjdmgpbokiacbbb\2015.1.2_0.

I tested the second computer that is also having this problem, and it too is crashing when I attempt to replace sandbox.html with the updated version.

Please let me know if I can provide any other information.

Thanks.

**Comment by aakash-shah** [comment]
Hello!  Just a friendly check in to see if I can provide any other information/logs/files that may help isolate the problem.  Thanks!

**Comment by babyman** [comment]
Hey, thanks for sticking with me on this, busy week... and I'm a bit stumped on this issue.  It's crazy that switching the sandbox.html files actually crashes your browser.  I'm digging around in the forums looking for anything similar other people are experiencing.

**Comment by aakash-shah** [comment]
No problem at all!  I appreciate all of your time and effort into this.

I did some more testing on my browser where I closed all of my 200+ tabs, as well as disabled all of my add-ons, and also reinstalled QuickTabs, and the problem persisted.  Then I remembered that I have disabled JavaScript by default at Settings | Advanced | Privacy | Content settings | Do not allow any site to run JavaScript.  With Javascript disabled, I use the "HTTP Status Bar" plugin to enable Javascript on sites where I need this.  I am able to reproduce this on-demand - with JavaScript disabled, QuickTabs stops working, and once I enable it, it begins to work.

I believe that I had made this change before I noticed this problem, but I am not sure.  What site do I need to set an exception for to allow Quick Tabs to run Javascript?  

Thanks!

**Comment by babyman** [comment]
That was it, if I disable JS in my Chrome settings I get the exact behaviour you describe, I expect this issue has been caused by a change I made to the template code to run in a sandbox.html page ( https://developer.chrome.com/extensions/sandboxingEval ) to stay ahead of any security issues.  This new extension sandbox.html page seems to honour the browser JS settings!

If you go to Settings | Advanced | Privacy | Content settings | Do not allow any site to run JavaScript | Manage exceptions... and allow the following url it should let the template code run properly:

chrome-extension://jnjfeinjfmenlddahdjdmgpbokiacbbb/

I sure hope this works for you.

![screen shot 2015-01-18 at 11 23 04 pm](https://cloud.githubusercontent.com/assets/120736/5796078/db59533a-9f6c-11e4-93de-5e67050fea87.png)

**Comment by aakash-shah** [comment]
That did the trick!  I tried this yesterday, but it appears that I needed to restart my browser and wait a few moments before it started to work.  Both browsers that previously had this problem are now working.

Thanks for your time and your help with this - I really appreciate it!
