### ISSUE TITLE
Odd behaviour when navigating with arrow keys

### ISSUE THREAD

**Issue by Fritte** [babyman/quick-tabs-chrome-extension#72]
If I have more than fifteen entries in my list, it sometimes occurs that if I press down not the next entry in the list is selected but an arbitrary one. This leads to not deterministic jumping through my tab list. 

OS: Xubuntu 14.04
Google Chrome: 40.0.2214.91

BR,
Fritte

**Comment by babyman** [comment]
Hi Fritte,

I have noticed that if the tab list opens under your mouse pointer the selection gets set to the location of the mouse, this can make thinks behave a little crazy, any chance this is what is happening?

Evan

**Comment by Fritte** [comment]
Hi Evan,

You are perfectly right, I was not paying attention to the position of my cursor.

Best Regards,
Fritte
