### ISSUE TITLE
new style does not work well with dark Chrome theme

### ISSUE THREAD

**Issue by X1011** [babyman/quick-tabs-chrome-extension#76]
It seems the style changes with today's release don't specify a background color along with the text color, so with my dark Chrome theme, the popup looks like this: 
![screenshot 2015-02-26 at 2 52 41 am](https://cloud.githubusercontent.com/assets/2611152/6388077/557b221a-bd63-11e4-9f9f-5236a87fe809.png)

**Comment by babyman** [comment]
@X1011 is this still an issue for you?  I tried a couple of dark themes from the store and cannot recreate this...
![screen shot 2015-02-26 at 10 39 35 pm](https://cloud.githubusercontent.com/assets/120736/6407139/7136e674-be08-11e4-97dd-8fd4e043e423.png)

**Comment by X1011** [comment]
hmm, after restarting Chrome, it's not happening for me anymore, either. Oh well, thanks for taking a look.
