### ISSUE TITLE
Explain new permission requirements in changelog

### ISSUE THREAD

**Issue by aioue** [babyman/quick-tabs-chrome-extension#77]
Please explain in the Chrome Web Store changelog why new permissions are needed.

![image](https://cloud.githubusercontent.com/assets/1254905/6403599/3f03ba06-be08-11e4-95f5-a3d980c1b0e9.png)

**Comment by babyman** [comment]
Great idea, I am planning to update the screen caps and I will make sure to include the reason for the additional bookmark access.  It is required to allow bookmarks to be included in the tab search results (read only).
