### ISSUE TITLE
How to apply custom css?

### ISSUE THREAD

**Issue by seatrout** [babyman/quick-tabs-chrome-extension#78]
I have tried simply placing the URL to the custom CSS file in the edit box on the options page. This does nothing. Are we meant to cut and paste the whole file from bunnyslippers into there? At the least, the instructions could be made clearer, and easier to follow for people who don't understand github.

**Comment by babyman** [comment]
@seatrout yes, you will need to copy and paste the CSS code into the custom css edit box (rather than the URL).  I will update the instructions to make this more clear.

Evan

**Comment by seatrout** [comment]
Thanks. I'll do this soonest.
