### ISSUE TITLE
Search tab by URL is not working if Show URLs is unchecked

### ISSUE THREAD

**Issue by sergeevabc** [babyman/quick-tabs-chrome-extension#81]
Dear Evan,

I do uncheck “Show URLs” option to have popup with list of tabs less cluttered, without noisy lines of small-sized site addresses, however it disables search by URL as well. Is it by design, or not? 

Imagine, tab name is “Welcome, sweethearts” and its address is “www.lovemetender.org” — presently keyword “love” will catch the tab only if checkbox is set. And I’d prefer to have it catched in both cases.

**Comment by babyman** [comment]
@sergeevabc, when urls are hidden the search only includes the page titles to avoid showing strange looking results.

**Comment by sergeevabc** [comment]
Indeed, results could look strange for those who use your extension for the first time.
However, advanced user would appreciate more flexibility, right?
So this possible option could be unset by default, with some warning message to rookies.

**Comment by sergeevabc** [comment]
Thank you, sir.
