### ISSUE TITLE
Bookmarks are not searched

### ISSUE THREAD

**Issue by sergeevabc** [babyman/quick-tabs-chrome-extension#82]
Dear Evan, good morning, and welcome to a new issue related to Quick Tabs.

Dunno how to be clear and precise on this one, but subject is as is—no bookmarks appear while trying their titles or addresses, just opened and recently closed tabs. Hmm, what else to add?

**Comment by babyman** [comment]
Bookmarks will only be searched if there are only a few tabs that match your search criteria or your search starts or ends with a space or 2.

**Comment by sergeevabc** [comment]
> or your search starts or ends with a space or 2
Wow, it works this way, perfectly as expected!
Thank you, sir.

**Comment by sergeevabc** [comment]
Evan, thank you very much for the latest improvement as follows
> 2015.4.17 - fixed issue opening urls when they contain search character matches
I was in a quandary on how to submit a report about this issue, literary was out of words. And now it’s settled.

**Comment by babyman** [comment]
I'm glad it's working for you, I only noticed the issue while is was working on the history search =)

**Comment by sergeevabc** [comment]
Evan, by the way, this new thing below makes QuicksTabs unresponsive for a long time.
> 2015.4.17 Added fuzzy history search by starting or ending the search string with 3 spaces

**Comment by babyman** [comment]
Hmm, the slowness is because I load and search your entire browser history without any caching or preloading, this keeps the memory footprint down.  It should only be slow when searching history, all other things should behave the same.
