### ISSUE TITLE
Feature request: option to show tabs from the active window only

### ISSUE THREAD

**Issue by yueluog** [babyman/quick-tabs-chrome-extension#83]
Can we get an option to show only the tabs in the active window?  In most cases, I only want to switch between tabs in the active window.  So an option setting to choose would be appreciated.

If we can get two keyboard shotcut, one for listing tabs in all windows and one for listing tabs in active window only, it would be even better.

**Comment by tv42** [comment]
I would love this feature. I group tabs into windows on purpose by context, and only want to see tabs in the current context.
