### ISSUE TITLE
QuickTabs recently disappeared from my extensions!

### ISSUE THREAD

**Issue by fcherman** [babyman/quick-tabs-chrome-extension#84]
As you know, I love this extension. Recently, I had deactivated some extensions (using Extensity), but Extensity cannot delete them. Today, I went to turn on QuickTabs, and it was GONE! It didn't even appear in my Chrome extensions list. Of course, I reinstalled it right away (and applied my custom styling that you so kindly featured in your screenshots). Have you heard of this happening to anyone else?

**Comment by babyman** [comment]
That is very strange, I know that Chrome has taken to deactivating QuickTabs every time I rollout an update (which is very frustrating and I have not found any details online yet) but I have not had anyone mention it being uninstalled :|

**Comment by fcherman** [comment]
Well, I'm keeping an eye on it. ;-)

**Comment by babyman** [comment]
duplicate of #79?
