### ISSUE TITLE
javascript bookmark breaks search

### ISSUE THREAD

**Issue by benbarth** [babyman/quick-tabs-chrome-extension#85]
When a search matches the following bookmark it breaks the view.

javascript:function reload(){setTimeout("reload()",1e3*timeout);var e=document.getElementById("refreshframe");e.contentWindow.location.reload()}if(timeout=prompt("Set timeout [s]"),current=location.href,timeout>0){var fr4me="<frameset cols='*'>\n<frame id=\"refreshframe\" src='"+current+"'/></frameset>";document.write(fr4me),setTimeout("reload()",1e3*timeout)}

![screen shot 2015-04-30 at 8 10 20 pm](https://cloud.githubusercontent.com/assets/1040797/7425089/bb5f6c66-ef78-11e4-90d5-74d5f1fb9717.png)

![screen shot 2015-04-30 at 7 57 17 pm](https://cloud.githubusercontent.com/assets/1040797/7425088/bb5f316a-ef78-11e4-8846-d0b9ba119851.png)

**Comment by benbarth** [comment]
I've developed a fix. I'll send a pull request.

**Comment by babyman** [comment]
I have too but yours might be better =)

**Comment by benbarth** [comment]
I used doT's built in encoding functionality. It was a small change.

**Comment by babyman** [comment]
for some reason I thought that was a little shaky with the JS code but it seems to work just fine so it makes sense to go with the simpler solution, thanks for taking the time to report and fix this, always appreciate the help =)

**Comment by benbarth** [comment]
Well, the root problem was the '<' character in the JS code. It needed to be html encoded.

Not a problem. I really like the extension so I'm happy to contribute!

**Comment by babyman** [comment]
I just uploaded the updated code to the Google Web Store so you should see it soon.
