### ISSUE TITLE
(Feature request) Add minimum time requirement for tabs to change order in list

### ISSUE THREAD

**Issue by mhavard999** [babyman/quick-tabs-chrome-extension#90]
Sometimes to get to a tab, I will just hold down Ctrl+Tab until I hit the tab, but this messes up the order of my tabs in the list because it registers every tab between the one I started on and the one I ended on.  It would be great if you could add something so that a page only changes it's position in the list if it has been active for at least one second.  Couldn't you put some sort of setTimeout thing in there?  idk I haven't browsed the source.

**Comment by babyman** [comment]
That's a great idea, I will take a look and see how best to implement this...

Evan

**Comment by mrzmyr** [comment]
+1
