### ISSUE TITLE
Keyboard shortcut for switching to last tab

### ISSUE THREAD

**Issue by mightyiam** [babyman/quick-tabs-chrome-extension#93]
Thank you for this extension.

Could you perhaps provide another keyboard shortcut,
for switching to the last tab (would be the first in the list, I guess)?

I don't care if the tab list opens for a flash, if that's required.

**Comment by mightyiam** [comment]
Thank you, @babyman! When do you think I'll get the release?

**Comment by mightyiam** [comment]
I'm not sure how extension updates work.

**Comment by babyman** [comment]
I just published it to the Chrome Store, your browser should download the update automatically (and probably disable it, a "security" feature).  If you check "Developer Mode" on the extensions page you can force an update.

Once updated set the keyboard shortcut keys using the "Keyboard shortcuts" link at the bottom of the extensions page.

**Comment by mightyiam** [comment]
The keyboard shortcuts are great, I set them to Ctrl+K/J. But they don't do what I expect. I'll file another issue for that.

**Comment by babyman** [comment]
Next/Prev navigates the tabs in the order displayed in the QuickTabs popup so pressing Prev will focus the top item in the list, pressing Prev again will move focus to the tab below that in the list etc. BUT if a tab is in focus for over 1.5 seconds it will become the current tab and move to the top of the tab list.

This means that the Next key will only work for about 1.5 seconds before the current tab becomes the focused tab in the list and therefore has no next entry.

Hope this helps.

**Comment by mightyiam** [comment]
@babyman thank you for the explanation.
This doesn't sound like what I would imagine to be an ideal behavior. I'm not sure, but perhaps without the timer thing it is.
