### ISSUE TITLE
Discussion: Ordering of the list

### ISSUE THREAD

**Issue by mrzmyr** [babyman/quick-tabs-chrome-extension#94]
As we got already #41 and the current ordering in discussion, I'd like to add my personal preference as well: It would be great if the list would be sorted by some kind of little magic, so it reminds to which tabs I tend to switch more often.

**Example**: I switch to the facebook messenger way more often than to my recent stackoverflow questions it shows the fb messenger tab at first in the list.

That behaviour is already implemented in "Command Palettes" of Sublime Text and Atom.

I may can provide a PR for that.

**Comment by mightyiam** [comment]
When I use the new keyboard shortcuts for next/previous, I don't get expected ordering. I get unexpected switching. I didn't make an effort at understanding the pattern.

**Comment by mightyiam** [comment]
New keyboard shortcuts from #93.

**Comment by mightyiam** [comment]
Or from 47d262257, more correctly.

**Comment by cloneman** [comment]
I also don't understand the ordering. Is there a way just to have the list in the same order as the tabs on top of the page? I don't like that the order changes as I switch around.

**Comment by dansteen** [comment]
Thanks so much for this plugin!  It's a nearly perfect tab manager.
I would like to have an option to show tabs in the order they exist in the browser as well.  I'm generally pretty spacial in my organization, and having everything in the same place that I left dramatically increases my speed.   so +1 for this as well.
