### ISSUE TITLE
Where do I begin? Is there a video tutorial on how to use this Chrome extension?

### ISSUE THREAD

**Issue by goughgough** [babyman/quick-tabs-chrome-extension#96]
Can somebody please tell me how to start using this Chrome extension?

I have searched everywhere and I cannot find any tip on how to begin to use it with my keyboard.

Yes, I have checked the Quick Tabs Options page at 
chrome-extension://jnjfeinjfmenlddahdjdmgpbokiacbbb/options.html

and I am still at a loss.

Please advise. Thanks a million.

**Comment by potmpark** [comment]
If you mean how to launch it by shortcut key, it's in the readme:
>shortcut key to launch popup window from most tabs, defaults to Ctrl + e, **configurable on the keyboard shortcuts page at the bottom of the Chrome Extensions page.**

**Comment by goughgough** [comment]
Thanks a million potmpark.

Finally I am able to start using it.

I did scan through the readme before seeking help.

Looks like the information on readme page should be organized better for dummies like me.

May be a separate section called "Usage tips" would have helped.

And your advice has helped me discover a part of Chrome extension I never knew existed. 

After all these years of using Google Chrome inefficiently, wow.
