### ISSUE TITLE
Fuzzy search is too fuzzy

### ISSUE THREAD

**Issue by Chriswaterguy** [babyman/quick-tabs-chrome-extension#97]
In search, the order of the letters entered is apparently irrelevant. I'd prefer the option of exact matching only, as this would let me find things quicker (especially when it comes to drilling into history or bookmarks).

**Comment by philippotto** [comment]
I'm also seeing some issues with the fuzzy matching. I just typed in "slack" and it highlighted as follows:

**s**ca**la**ble ... - sla**ck**

I don't really care if it highlights the correct substrings, as long as it finds the desired things, but the thing is that the order in the list gets scrambled by this.

**Comment by babyman** [comment]
There is definitely room to improve the fuzzy search, in earlier versions of the extension I had exact matching but it was far to restrictive.

The current fuzzy search matches the search characters in order against the page title and url (if shown) and ranks consecutive character matches more highly.  The tab list is then sorted by match score.

I will take a look and see how I can improve (or replace) the current matching.

E

**Comment by brendan-peerstreet** [comment]
May I suggest that the fuzzy search still searches for any consecutive group of characters together?  So, if I type in "slack", the "slack" has to appear together, but it can appear with any amount of prefix or postfix.  If however I type in "slack more", "slack" and "more" each have to be appear, but there can be any number of characters in between "slack" and "more".

The current implementation, especially since any short word will match several crazy url's, makes the list quite messy and difficult to find.

Alternatively, make this an option

**Comment by malcook** [comment]
+1 - I really like every other aspect of this tool - just way too fuzzy - and non-intuitive -  an option for exact match would be great - and fuzzy but less fuzzy would be great too - you seem to require all the characters in the search term to appear in the same order in the hit, including spaces, this is very strange  - perhaps consider something like this implementation of fuzzy: http://www.listjs.com/docs/plugins/fuzzysearch

THANKS FOR QUICK_TABS

**Comment by djbclark** [comment]
+1 Yeah this is really offputting. I'd like zero fuzzy search.

**Comment by vitriolix** [comment]
+1

My #1 (and only) complaint with this extension.  99.9% of the time the search turns up totally irrelevant results

**Comment by botsmack** [comment]
I agree. The search is too fuzzy for me. Everything else is great.

**Comment by malcook** [comment]
Alas, in the mean time, I use https://chrome.google.com/webstore/detail/fast-tab-switcher/jkhfenkikopkkpboaipgllclaaehgpjf

**Comment by cburkins** [comment]
Really love Quick Tabs, but the fuzzy search is definitely too fuzzy.   Consecutive letters should be weighted more heavily.   Whole matching words should def be at the top of the list.   In the meantime, continuing to search for a different solution, any ideas ?

**Comment by botsmack** [comment]
Tabman Tabs Manager has been updated (as of 13-Jun-2016) and it's always been my favorite in terms of searching. Originally I used it, but it hadn't been updated to fix some bugs, so I went searching for a replacement. The one thing I love about Tabman Tabs Manager is the search only displays what you're searching for. Results that aren't related, do not show up. So much easier to read.

https://chrome.google.com/webstore/detail/tabman-tabs-manager/hgmnkflcjcohihpdcniifjbafcdelhlm

**Comment by rajington** [comment]
If you guys know how to try unpacked extensions, I encourage you to look at [my branch](https://github.com/rajington/quick-tabs-chrome-extension/tree/switch-fuzzy-to-fuse) and see if it looks better. The results are ordered much better for me, but the library I switched it to is highly configurable so if you're still getting results that don't make sense I can tweak things.
