### ISSUE TITLE
How to increase list height?

### ISSUE THREAD

**Issue by nab128** [babyman/quick-tabs-chrome-extension#98]
Can't seem to find the right CSS for this!

body {
    max-height: 1000px;
    height: 1000px;
}

div.content {
    height: 1000px;
}

What else can I try?

**Comment by babyman** [comment]
Chrome imposes height and width limits on the extension windows and seems to pretty much ignore the height property :|

http://stackoverflow.com/questions/8983165/how-can-i-expand-the-popup-window-of-my-chrome-extension

and

https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/nJIWEuJpI3Y
