### ISSUE TITLE
Remove Cmd-K shortcut

### ISSUE THREAD

**Issue by danvk** [babyman/quick-tabs-chrome-extension#99]
Command-K is very widely used across the web (e.g. in Gmail, Google docs) to insert links. It took me a few minutes this morning to debug why this shortcut suddenly stopped working. Eventually I traced it back to Quick Tabs.

This is pretty disruptive to set by default.

**Comment by babyman** [comment]
Thanks @danvk, I was in two minds about mapping ctrl+J/K by default but couldn't see any key conflicts within Chrome itself (except to view the downloads page).  If Google is using ctrl+K I will leave the shortcuts unmapped to keep things simple/unobtrusive.

**Comment by mattsson** [comment]
So, how do I bind a custom key to the extension now?

**Comment by babyman** [comment]
@mattsson you can map shortcut keys using the "Keyboard shortcuts" link at the bottom of the Chrome extensions settings page, mine looks like this:

![screen shot 2015-10-21 at 9 51 10 am](https://cloud.githubusercontent.com/assets/120736/10638516/524a66b0-77d9-11e5-9f7e-125e0e15f450.png)

The next/Previous tab options default to unset to avoid unexpected behaviors like the one described here.

**Comment by mattsson** [comment]
Great, thanks! What an odd place to put that.

**Comment by jessergibson** [comment]
@babyman I just felt compelled to offer you my heartiest thanks. That fucking shortcut has been bugging the crap out of me for years and I could never solve the problem until I stumbled across this post. You, sir, are a genius.
